[package]
name = "pezkuwi-collator-protocol"
version = "22.0.0"
description = "Pezkuwi Collator Protocol subsystem. Allows collators and validators to talk to each other."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bitvec = { features = ["alloc"], workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
gum.default-features = true
gum.workspace = true
schnellru.workspace = true
sp-core.default-features = true
sp-core.workspace = true
sp-keystore.default-features = true
sp-keystore.workspace = true
sp-runtime.default-features = true
sp-runtime.workspace = true

fatality = { workspace = true }
pezkuwi-node-network-protocol.default-features = true
pezkuwi-node-network-protocol.workspace = true
pezkuwi-node-primitives.default-features = true
pezkuwi-node-primitives.workspace = true
pezkuwi-node-subsystem-util.default-features = true
pezkuwi-node-subsystem-util.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
thiserror = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
rstest = { workspace = true }
sp-tracing = { default-features = false, workspace = true }

codec = { features = ["std"], workspace = true, default-features = true }
sc-keystore = { default-features = true, workspace = true }
sc-network = { default-features = true, workspace = true }
sp-core = { features = ["std"], default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }

pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives-test-helpers = { workspace = true }

[features]
default = []
