[package]
name = "pezkuwi-approval-distribution"
version = "22.0.0"
description = "Pezkuwi Approval Distribution subsystem for the distribution of assignments and approvals for approval checks on candidates over the network."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
itertools = { workspace = true }
pezkuwi-node-metrics.default-features = true
pezkuwi-node-metrics.workspace = true
pezkuwi-node-network-protocol.default-features = true
pezkuwi-node-network-protocol.workspace = true
pezkuwi-node-primitives.default-features = true
pezkuwi-node-primitives.workspace = true
pezkuwi-node-subsystem-util.default-features = true
pezkuwi-node-subsystem-util.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
rand = { workspace = true, default-features = true }

futures = { workspace = true }
futures-timer = { workspace = true }
gum.default-features = true
gum.workspace = true

[dev-dependencies]
sc-keystore = { default-features = false, workspace = true }
sp-application-crypto = { default-features = true, workspace = true }
sp-authority-discovery = { default-features = true, workspace = true }
sp-core = { features = ["std"], default-features = true, workspace = true }

pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives-test-helpers = { workspace = true }

assert_matches = { workspace = true }
rand_chacha = { workspace = true, default-features = true }
schnorrkel = { workspace = true }
# rand_core should match schnorrkel
rand_core = { workspace = true }
sp-tracing = { default-features = false, workspace = true }
