[package]
name = "cumulus-relay-chain-streams"
version = "0.7.0"
authors.workspace = true
description = "Cumulus client common relay chain streams."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
tracing = { workspace = true, default-features = true }

# Substrate
sp-api = { workspace = true, default-features = true }
sp-consensus = { workspace = true, default-features = true }

# Pezkuwi
pezkuwi-node-subsystem = { workspace = true, default-features = true }
pezkuwi-primitives = { workspace = true, default-features = true }

# Cumulus
cumulus-relay-chain-interface = { workspace = true, default-features = true }

[features]
runtime-benchmarks = [
	"cumulus-relay-chain-interface/runtime-benchmarks",
	"pezkuwi-node-subsystem/runtime-benchmarks",
	"pezkuwi-primitives/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
]
