[package]
name = "pezkuwi-zombienet-sdk-tests"
version = "0.1.0"
description = "Zomebienet-sdk tests."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
documentation = "https://docs.rs/pezkuwi-zombienet-sdk-tests"
repository = { workspace = true }
homepage = { workspace = true }

[dependencies]
anyhow = { workspace = true }
asset-hub-zagros-runtime = { workspace = true }
codec = { workspace = true, features = ["derive"] }
pezcumulus-zombienet-sdk-helpers = { workspace = true }
env_logger = { workspace = true }
ethabi = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
pezpallet-revive = { workspace = true, features = ["std"] }
pezkuwi-primitives = { workspace = true, default-features = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pezsp-core = { workspace = true }
subxt = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util = { workspace = true, features = ["time"] }
zombienet-orchestrator = { workspace = true }
zombienet-sdk = { workspace = true }

[features]
zombie-metadata = []
zombie-ci = []
runtime-benchmarks = [
  "asset-hub-zagros-runtime/runtime-benchmarks",
  "pezcumulus-zombienet-sdk-helpers/runtime-benchmarks",
  "pezpallet-revive/runtime-benchmarks",
  "pezkuwi-primitives/runtime-benchmarks",
  "pezsc-executor/runtime-benchmarks",
  "pezsc-runtime-utilities/runtime-benchmarks",
  "pezsp-io/runtime-benchmarks",
]

[build-dependencies]
pezsc-executor = { workspace = true, default-features = true }
pezsc-runtime-utilities = { workspace = true, default-features = true }
pezsp-io = { workspace = true }
bizinikiwi-build-script-utils = { workspace = true, default-features = true }
