// This file is part of Bizinikiwi.

// Copyright (C) Parity Technologies (UK) Ltd. and Dijital Kurdistan Tech Institute
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Implementation of `runtime`.
//!
//! `runtime` implementation is recursive and can generate code which will call itself
//! in order to get all the pezpallet parts for each pezpallet.
//!
//! Pallets can define their parts:
//!  - Implicitly: `pub type System = pezframe_system;`
//!  - Explicitly: `pub type System = pezframe_system + Pezpallet + Call;`
//!
//! The `runtime` transitions from the implicit definition to the explicit one.
//! From the explicit state, Bizinikiwi expands the pallets with additional information
//! that is to be included in the runtime metadata.
//!
//! Pallets must provide the `tt_default_parts_v2` macro for these transitions.
//! These are automatically implemented by the `#[pezpallet::pezpallet]` macro.
//!
//! This macro also generates the following enums for ease of decoding if the respective type
//! is defined inside `#[runtime::derive]`:
//!  - `enum RuntimeCall`: This type contains the information needed to decode extrinsics.
//!  - `enum RuntimeEvent`: This type contains the information needed to decode events.
//!  - `enum RuntimeError`: While this cannot be used directly to decode
//!    `pezsp_runtime::DispatchError` from the chain, it contains the information needed to decode
//!    the `pezsp_runtime::DispatchError::Module`.
//!
//! # State Transitions
//!
//! ```ignore
//!  +----------+
//!  | Implicit |
//!  +----------+           
//!      |                  
//!      v                  
//!  +----------+
//!  | Explicit |
//!  +----------+
//! ```
//!
//! The `runtime` macro transforms the implicit declaration of each pezpallet
//! `System: pezframe_system` to an explicit one `System: pezframe_system + Pezpallet + Call` using
//! the `tt_default_parts_v2` macro.
//!
//! The `tt_default_parts_v2` macro exposes a plus separated list of pezpallet parts. For example,
//! the `Event` part is exposed only if the pezpallet implements an event via `#[pezpallet::event]`
//! macro. The tokens generated by this macro are `+ Pezpallet + Call` for our example.
//!
//! The `match_and_insert` macro takes in 3 arguments:
//!  - target: This is the `TokenStream` that contains the `runtime` macro.
//!  - pattern: The pattern to match against in the target stream.
//!  - tokens: The tokens to added after the pattern match.
//!
//! The `runtime` macro uses the `tt_call` to get the default pezpallet parts via
//! the `tt_default_parts_v2` macro defined by each pezpallet. The pezpallet parts are then returned
//! as input to the `match_and_replace` macro.
//! The `match_and_replace` then will modify the `runtime` to expand the implicit
//! definition to the explicit one.
//!
//! For example,
//!
//! ```ignore
//! #[pezframe_support::runtime]
//! mod runtime {
//! 	//...
//!
//!     #[runtime::pezpallet_index(0)]
//! 	pub type System = pezframe_system; // Implicit definition of parts
//!
//!     #[runtime::pezpallet_index(1)]
//! 	pub type Balances = pezpallet_balances; // Implicit definition of parts
//! }
//! ```
//! This call has some implicit pezpallet parts, thus it will expand to:
//! ```ignore
//! pezframe_support::__private::tt_call! {
//! 	macro = [{ pezpallet_balances::tt_default_parts_v2 }]
//! 	~~> pezframe_support::match_and_insert! {
//! 		target = [{
//! 			pezframe_support::__private::tt_call! {
//! 				macro = [{ pezframe_system::tt_default_parts_v2 }]
//! 				~~> pezframe_support::match_and_insert! {
//! 					target = [{
//!                         #[pezframe_support::runtime]
//!                         mod runtime {
//! 	                        //...
//!
//!                             #[runtime::pezpallet_index(0)]
//! 		                    pub type System = pezframe_system;
//!                             
//! 							#[runtime::pezpallet_index(1)]
//! 		                    pub type Balances = pezpallet_balances;
//!                         }
//! 					}]
//! 					pattern = [{ System = pezframe_system }]
//! 				}
//! 			}
//! 		}]
//! 		pattern = [{ Balances = pezpallet_balances }]
//! 	}
//! }
//! ```
//! `tt_default_parts_v2` must be defined. It returns the pezpallet parts inside some tokens, and
//! then `tt_call` will pipe the returned pezpallet parts into the input of `match_and_insert`.
//! Thus `match_and_insert` will initially receive the following inputs:
//! ```ignore
//! pezframe_support::match_and_insert! {
//! 	target = [{
//! 		pezframe_support::match_and_insert! {
//! 			target = [{
//!                  #[pezframe_support::runtime]
//!                  mod runtime {
//! 	                 //...
//!
//!                      #[runtime::pezpallet_index(0)]
//! 		             pub type System = pezframe_system;
//!
//!                      #[runtime::pezpallet_index(1)]
//! 		             pub type Balances = pezpallet_balances;
//!                  }
//! 			}]
//! 			pattern = [{ System = pezframe_system }]
//! 			tokens = [{ ::{+ Pezpallet + Call} }]
//! 		}
//! 	}]
//! 	pattern = [{ Balances = pezpallet_balances }]
//! 	tokens = [{ ::{+ Pezpallet + Call} }]
//! }
//! ```
//! After dealing with `pezpallet_balances`, the inner `match_and_insert` will expand to:
//! ```ignore
//! pezframe_support::match_and_insert! {
//! 	target = [{
//! 		#[pezframe_support::runtime]
//!         mod runtime {
//! 	        //...
//!
//!             #[runtime::pezpallet_index(0)]
//! 		    pub type System = pezframe_system; // Implicit definition of parts
//!
//!             #[runtime::pezpallet_index(1)]
//! 		    pub type Balances = pezpallet_balances + Pezpallet + Call; // Explicit definition of parts
//!         }
//! 	}]
//! 	pattern = [{ System = pezframe_system }]
//! 	tokens = [{ ::{+ Pezpallet + Call} }]
//! }
//! ```
//!
//! Which will then finally expand to the following:
//! ```ignore
//! #[pezframe_support::runtime]
//! mod runtime {
//! 	//...
//!
//!     #[runtime::pezpallet_index(0)]
//! 	pub type System = pezframe_system + Pezpallet + Call;
//!
//!     #[runtime::pezpallet_index(1)]
//! 	pub type Balances = pezpallet_balances + Pezpallet + Call;
//! }
//! ```
//!
//! This call has no implicit pezpallet parts, thus it will expand to the runtime construction:
//! ```ignore
//! pub struct Runtime { ... }
//! pub struct Call { ... }
//! impl Call ...
//! pub enum Origin { ... }
//! ...
//! ```
//!
//! Visualizing the entire flow of `#[pezframe_support::runtime]`, it would look like the following:
//!
//! ```ignore
//! +----------------------+     +------------------------+     +-------------------+
//! |                      |     | (defined in pezpallet)    |     |                   |
//! | runtime              | --> |  tt_default_parts_v2!  | --> | match_and_insert! |
//! | w/ no pezpallet parts   |     |                        |     |                   |
//! +----------------------+     +------------------------+     +-------------------+
//!
//!     +----------------------+
//!     |                      |
//! --> | runtime              |
//!     |  w/ pezpallet parts     |
//!     +----------------------+
//! ```

pub use parse::Def;
use proc_macro::TokenStream;
use syn::spanned::Spanned;

mod expand;
mod parse;

mod keyword {
	syn::custom_keyword!(legacy_ordering);
}

pub fn runtime(attr: TokenStream, tokens: TokenStream) -> TokenStream {
	let mut legacy_ordering = false;
	if !attr.is_empty() {
		if let Ok(_) = syn::parse::<keyword::legacy_ordering>(attr.clone()) {
			legacy_ordering = true;
		} else {
			let msg = "Invalid runtime macro call: unexpected attribute. Macro call must be \
				bare, such as `#[pezframe_support::runtime]` or `#[runtime]`, or must specify the \
				`legacy_ordering` attribute, such as `#[pezframe_support::runtime(legacy_ordering)]` or \
				#[runtime(legacy_ordering)].";
			let span = proc_macro2::TokenStream::from(attr).span();
			return syn::Error::new(span, msg).to_compile_error().into();
		}
	}

	let item = syn::parse_macro_input!(tokens as syn::ItemMod);
	match parse::Def::try_from(item) {
		Ok(def) => expand::expand(def, legacy_ordering).into(),
		Err(e) => e.to_compile_error().into(),
	}
}
