[package]
name = "cumulus-test-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }

# Substrate
frame-system = { workspace = true, default-features = true }
pallet-balances = { workspace = true, default-features = true }
pallet-transaction-payment = { workspace = true, default-features = true }
sc-block-builder = { workspace = true, default-features = true }
sc-consensus = { workspace = true, default-features = true }
sc-consensus-aura = { workspace = true, default-features = true }
sc-executor = { workspace = true, default-features = true }
sc-executor-common = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-application-crypto = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-consensus-aura = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-inherents = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-timestamp = { workspace = true, default-features = true }
substrate-test-client = { workspace = true }

# Pezkuwi
pezkuwi-primitives = { workspace = true, default-features = true }
pezkuwi-teyrchain-primitives = { workspace = true, default-features = true }

# Cumulus
cumulus-pallet-weight-reclaim = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-primitives-proof-size-hostfunction = { workspace = true, default-features = true }
cumulus-primitives-teyrchain-inherent = { workspace = true, default-features = true }
cumulus-test-relay-sproof-builder = { workspace = true, default-features = true }
cumulus-test-runtime = { workspace = true }
cumulus-test-service = { workspace = true }

[features]
runtime-benchmarks = [
	"cumulus-pallet-weight-reclaim/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-test-service/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pezkuwi-primitives/runtime-benchmarks",
	"pezkuwi-teyrchain-primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"cumulus-primitives-teyrchain-inherent/runtime-benchmarks",
	"cumulus-test-relay-sproof-builder/runtime-benchmarks",
	"cumulus-test-runtime/runtime-benchmarks",
	"sc-block-builder/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-consensus-aura/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus-aura/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"substrate-test-client/runtime-benchmarks"
]
