// This file is part of Bizinikiwi.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for ``
//!
//! THIS FILE WAS AUTO-GENERATED USING THE BIZINIKIWI BENCHMARK CLI VERSION 32.0.1
//! DATE: 2026-03-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/pezframe-omni-bencher
// v1
// benchmark
// pezpallet
// --runtime
// target/release/wbuild/people-pezkuwichain-runtime/people_pezkuwichain_runtime.compact.compressed.wasm
// --pallet
// pezpallet_messaging
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pezcumulus/teyrchains/pezpallets/messaging/src/weights.rs
// --template
// bizinikiwi/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use pezframe_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for ``.
pub trait WeightInfo {
	fn register_encryption_key() -> Weight;
	fn send_message(l: u32, ) -> Weight;
	fn acknowledge_messages() -> Weight;
	fn cleanup_era(n: u32, ) -> Weight;
}

/// Weights for `` using the Bizinikiwi node and recommended hardware.
pub struct BizinikiwiWeight<T>(PhantomData<T>);
impl<T: pezframe_system::Config> WeightInfo for BizinikiwiWeight<T> {
	/// Storage: `Messaging::EncryptionKeys` (r:0 w:1)
	/// Proof: `Messaging::EncryptionKeys` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn register_encryption_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_187_000 picoseconds.
		Weight::from_parts(18_822_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Messaging::EncryptionKeys` (r:1 w:0)
	/// Proof: `Messaging::EncryptionKeys` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::CurrentEra` (r:1 w:0)
	/// Proof: `Messaging::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::SendCount` (r:1 w:1)
	/// Proof: `Messaging::SendCount` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Inbox` (r:1 w:1)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 512]`.
	fn send_message(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `64127`
		// Minimum execution time: 25_457_000 picoseconds.
		Weight::from_parts(39_707_432, 64127)
			// Standard Error: 1_806
			.saturating_add(Weight::from_parts(2_382, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Messaging::CurrentEra` (r:1 w:0)
	/// Proof: `Messaging::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Inbox` (r:1 w:0)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	fn acknowledge_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `64127`
		// Minimum execution time: 17_202_000 picoseconds.
		Weight::from_parts(22_612_000, 64127)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `Messaging::Inbox` (r:100 w:100)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn cleanup_era(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `88 + n * (54 ±0)`
		//  Estimated: `990 + n * (63137 ±0)`
		// Minimum execution time: 7_091_000 picoseconds.
		Weight::from_parts(11_022_205, 990)
			// Standard Error: 24_712
			.saturating_add(Weight::from_parts(1_464_351, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 63137).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Messaging::EncryptionKeys` (r:0 w:1)
	/// Proof: `Messaging::EncryptionKeys` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn register_encryption_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_187_000 picoseconds.
		Weight::from_parts(18_822_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Messaging::EncryptionKeys` (r:1 w:0)
	/// Proof: `Messaging::EncryptionKeys` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::CurrentEra` (r:1 w:0)
	/// Proof: `Messaging::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::SendCount` (r:1 w:1)
	/// Proof: `Messaging::SendCount` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Inbox` (r:1 w:1)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 512]`.
	fn send_message(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `64127`
		// Minimum execution time: 25_457_000 picoseconds.
		Weight::from_parts(39_707_432, 64127)
			// Standard Error: 1_806
			.saturating_add(Weight::from_parts(2_382, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Messaging::CurrentEra` (r:1 w:0)
	/// Proof: `Messaging::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Messaging::Inbox` (r:1 w:0)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	fn acknowledge_messages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `64127`
		// Minimum execution time: 17_202_000 picoseconds.
		Weight::from_parts(22_612_000, 64127)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `Messaging::Inbox` (r:100 w:100)
	/// Proof: `Messaging::Inbox` (`max_values`: None, `max_size`: Some(60662), added: 63137, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn cleanup_era(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `88 + n * (54 ±0)`
		//  Estimated: `990 + n * (63137 ±0)`
		// Minimum execution time: 7_091_000 picoseconds.
		Weight::from_parts(11_022_205, 990)
			// Standard Error: 24_712
			.saturating_add(Weight::from_parts(1_464_351, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 63137).saturating_mul(n.into()))
	}
}
