[relaychain]
default_image = "parity/pezkuwi:latest"
default_command = "pezkuwi"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain = "asset-hub-rococo-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/pezkuwi-parachain:latest"
command = "pezkuwi-parachain"
args = ["--force-authoring"]
