[package]
name = "bridge-hub-test-utils"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
description = "Utils for BridgeHub testing"
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive", "max-encoded-len"], workspace = true }
impl-trait-for-tuples = { workspace = true }
tracing = { workspace = true }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-utility = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-tracing = { workspace = true, default-features = true }

# Cumulus
asset-test-utils = { workspace = true, default-features = true }
cumulus-pallet-teyrchain-system = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
teyrchains-common = { workspace = true }
teyrchains-runtimes-test-utils = { workspace = true }

# Pezkuwi
pallet-xcm = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }

# Bridges
bp-header-chain = { workspace = true }
bp-messages = { workspace = true }
bp-pezkuwi-core = { workspace = true }
bp-relayers = { workspace = true }
bp-runtime = { workspace = true }
bp-test-utils = { workspace = true }
bp-teyrchains = { workspace = true }
pallet-bridge-grandpa = { workspace = true }
pallet-bridge-messages = { features = ["test-helpers"], workspace = true }
pallet-bridge-relayers = { workspace = true }
pallet-bridge-teyrchains = { workspace = true }
pallet-xcm-bridge-hub = { workspace = true }

[features]
default = ["std"]
std = [
	"asset-test-utils/std",
	"bp-header-chain/std",
	"bp-messages/std",
	"bp-pezkuwi-core/std",
	"bp-relayers/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	"bp-teyrchains/std",
	"codec/std",
	"cumulus-pallet-teyrchain-system/std",
	"cumulus-pallet-xcmp-queue/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-bridge-grandpa/std",
	"pallet-bridge-messages/std",
	"pallet-bridge-relayers/std",
	"pallet-bridge-teyrchains/std",
	"pallet-timestamp/std",
	"pallet-utility/std",
	"pallet-xcm-bridge-hub/std",
	"pallet-xcm/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"teyrchains-common/std",
	"teyrchains-runtimes-test-utils/std",
	"tracing/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]
runtime-benchmarks = [
	"asset-test-utils/runtime-benchmarks",
	"bp-header-chain/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-pezkuwi-core/runtime-benchmarks",
	"bp-relayers/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"bp-test-utils/runtime-benchmarks",
	"bp-teyrchains/runtime-benchmarks",
	"cumulus-pallet-teyrchain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bridge-grandpa/runtime-benchmarks",
	"pallet-bridge-messages/runtime-benchmarks",
	"pallet-bridge-relayers/runtime-benchmarks",
	"pallet-bridge-teyrchains/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"pallet-xcm-bridge-hub/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"teyrchains-runtimes-test-utils/runtime-benchmarks"
]
