[package]
name = "bp-beefy"
description = "Primitives of pezpallet-bridge-beefy module."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
publish = false
documentation.workspace = true
homepage = { workspace = true }

[lints]
workspace = true

[dependencies]
codec = { features = ["bit-vec", "derive"], workspace = true }
scale-info = { features = ["bit-vec", "derive"], workspace = true }
serde = { features = ["alloc", "derive"], workspace = true }

# Bridge Dependencies
pezbp-runtime = { workspace = true }

# Bizinikiwi Dependencies
binary-merkle-tree = { workspace = true }
pezframe-support = { workspace = true }
pezpallet-beefy-mmr = { workspace = true }
pezpallet-mmr = { workspace = true }
pezsp-consensus-beefy = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"binary-merkle-tree/std",
	"codec/std",
	"pezbp-runtime/std",
	"pezframe-support/std",
	"pezpallet-beefy-mmr/std",
	"pezpallet-mmr/std",
	"pezsp-consensus-beefy/std",
	"pezsp-runtime/std",
	"pezsp-std/std",
	"scale-info/std",
	"serde/std",
]
runtime-benchmarks = [
	"binary-merkle-tree/runtime-benchmarks",
	"pezbp-runtime/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezpallet-beefy-mmr/runtime-benchmarks",
	"pezpallet-mmr/runtime-benchmarks",
	"pezsp-consensus-beefy/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
