[settings]
timeout = 180
provider = "native"

[relaychain]
default_command = "/home/mamostehp/pezkuwi-sdk/target/release/pezkuwi"
chain = "pezkuwichain-local"
default_args = ["--unsafe-force-node-key-generation", "-lteyrchain=debug"]

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9946

[[teyrchains]]
id = 1000
chain = "asset-hub-pezkuwichain-local"
cumulus_based = true
add_to_genesis = true

[[teyrchains.collators]]
name = "DRQasimlo"
command = "/home/mamostehp/pezkuwi-sdk/target/release/pezkuwi-teyrchain"
rpc_port = 9945
args = ["--unsafe-force-node-key-generation", "-lteyrchain=debug"]
