[package]
name = "pezpallet-bridge-teyrchains"
version = "0.7.0"
description = "Module that allows bridged relay chains to exchange information on their teyrchains' heads."
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
documentation = "https://docs.rs/pezpallet-bridge-teyrchains"
homepage = { workspace = true }

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
tracing = { workspace = true }

# Bridge Dependencies
bp-header-pez-chain = { workspace = true }
bp-pezkuwi-core = { workspace = true }
bp-teyrchains = { workspace = true }
pezbp-runtime = { workspace = true }
pezpallet-bridge-grandpa = { workspace = true }

# Bizinikiwi Dependencies
pezframe-benchmarking = { optional = true, workspace = true }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-std = { workspace = true }

[dev-dependencies]
bp-header-pez-chain = { workspace = true, default-features = true }
bp-test-utils = { workspace = true, default-features = true }
pezsp-core = { workspace = true, default-features = true }
pezsp-io = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"bp-header-pez-chain/std",
	"bp-pezkuwi-core/std",
	"bp-teyrchains/std",
	"codec/std",
	"pezbp-runtime/std",
	"pezframe-benchmarking/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezpallet-bridge-grandpa/std",
	"pezsp-runtime/std",
	"pezsp-std/std",
	"scale-info/std",
	"tracing/std",
]
runtime-benchmarks = [
	"bp-header-pez-chain/runtime-benchmarks",
	"bp-pezkuwi-core/runtime-benchmarks",
	"bp-test-utils/runtime-benchmarks",
	"bp-teyrchains/runtime-benchmarks",
	"pezbp-runtime/runtime-benchmarks",
	"pezframe-benchmarking/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezpallet-bridge-grandpa/runtime-benchmarks",
	"pezsp-io/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
try-runtime = [
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezpallet-bridge-grandpa/try-runtime",
	"pezsp-runtime/try-runtime",
]
