[package]
name = "pezpallet-paged-list-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzz storage types of pezpallet-paged-list"
publish = false
documentation = "https://docs.rs/pezpallet-paged-list-fuzzer"

[lints]
workspace = true

[[bin]]
name = "pezpallet-paged-list-fuzzer"
path = "src/paged_list.rs"

[dependencies]
arbitrary = { workspace = true }
frame = { workspace = true, features = ["runtime"] }
honggfuzz = { workspace = true }
pezpallet-paged-list = { features = ["std"], workspace = true }

[features]
default = ["std"]
std = ["frame/std", "pezpallet-paged-list/std"]
runtime-benchmarks = [
  "frame/runtime-benchmarks",
  "pezpallet-paged-list/runtime-benchmarks",
]
