[package]
name = "test-parachain-undying"
description = "Test parachain for zombienet integration tests"
build = "build.rs"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
dlmalloc = { features = ["global"], workspace = true }
log = { workspace = true }
pezkuwi-parachain-primitives = { features = ["wasm-api"], workspace = true }
pezkuwi-primitives.default-features = false
pezkuwi-primitives.workspace = true
sp-io = { features = ["disable_allocator"], workspace = true }
tiny-keccak = { features = ["keccak"], workspace = true }

[build-dependencies]
substrate-wasm-builder.default-features = true
substrate-wasm-builder.workspace = true

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"pezkuwi-parachain-primitives/std",
	"pezkuwi-primitives/std",
	"sp-io/std",
]
