[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "pezkuwi"

[[relaychain.node_groups]]
name = "validator"
count = 3
args = ["--log=beefy=debug", "--enable-offchain-indexing=true"]

[[relaychain.nodes]]
name = "validator-unstable"
args = ["--log=beefy=debug", "--enable-offchain-indexing=true"]
