[package]
name = "pezkuwi-node-core-chain-api"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "The Chain API subsystem provides access to chain related utility functions like block number to hash conversions."
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.default-features = true
gum.workspace = true
pezkuwi-node-metrics.default-features = true
pezkuwi-node-metrics.workspace = true
pezkuwi-node-subsystem-types.default-features = true
pezkuwi-node-subsystem-types.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
sc-client-api.default-features = true
sc-client-api.workspace = true
sc-consensus-babe.default-features = true
sc-consensus-babe.workspace = true

[dev-dependencies]
codec = { workspace = true, default-features = true }
futures = { features = ["thread-pool"], workspace = true }
maplit = { workspace = true }
pezkuwi-node-primitives = { default-features = true, workspace = true }
pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives = { default-features = true, workspace = true }
sp-blockchain = { default-features = true, workspace = true }
sp-core = { default-features = true, workspace = true }
