[package]
name = "pezpallet-people"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Personhood-tracking pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, features = ["derive"] }
pezframe-benchmarking = { workspace = true, optional = true }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
log = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
pezsp-arithmetic = { workspace = true }
pezsp-core = { workspace = true }
pezsp-io = { workspace = true }
pezsp-runtime = { workspace = true }
verifiable = { workspace = true, features = ["small-ring"] }


[features]
default = ["std"]
std = [
	"codec/std",
	"pezframe-benchmarking?/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"log/std",
	"scale-info/std",
	"pezsp-arithmetic/std",
	"pezsp-core/std",
	"pezsp-io/std",
	"pezsp-runtime/std",
	"verifiable/std",
]
runtime-benchmarks = [
	"pezframe-benchmarking/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezsp-io/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"verifiable/no-std-prover",
]
try-runtime = [
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezsp-runtime/try-runtime",
]
