[package]
name = "mmr-gadget"
version = "29.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "MMR Client gadget for bizinikiwi"
homepage.workspace = true
documentation = "https://docs.rs/mmr-gadget"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
pezsc-client-api = { workspace = true, default-features = true }
pezsc-offchain = { workspace = true, default-features = true }
pezsp-api = { workspace = true, default-features = true }
pezsp-blockchain = { workspace = true, default-features = true }
pezsp-consensus = { workspace = true, default-features = true }
pezsp-consensus-beefy = { workspace = true, default-features = true }
pezsp-core = { workspace = true, default-features = true }
pezsp-mmr-primitives = { workspace = true, default-features = true }
pezsp-runtime = { workspace = true, default-features = true }

[dev-dependencies]
parking_lot = { workspace = true, default-features = true }
pezsc-block-builder = { workspace = true, default-features = true }
pezsp-tracing = { workspace = true, default-features = true }
bizinikiwi-test-runtime-client = { workspace = true }
tokio = { workspace = true, default-features = true }

[features]
runtime-benchmarks = [
  "pezsc-block-builder/runtime-benchmarks",
  "pezsc-client-api/runtime-benchmarks",
  "pezsc-offchain/runtime-benchmarks",
  "pezsp-api/runtime-benchmarks",
  "pezsp-blockchain/runtime-benchmarks",
  "pezsp-consensus-beefy/runtime-benchmarks",
  "pezsp-consensus/runtime-benchmarks",
  "pezsp-mmr-primitives/runtime-benchmarks",
  "pezsp-runtime/runtime-benchmarks",
  "bizinikiwi-test-runtime-client/runtime-benchmarks",
]
