[package]
name = "pezkuwi-node-core-bitfield-signing"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Bitfield signing subsystem for the Pezkuwi node"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum.default-features = true
gum.workspace = true
pezkuwi-node-subsystem-util.default-features = true
pezkuwi-node-subsystem-util.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
sp-keystore.default-features = true
sp-keystore.workspace = true
thiserror = { workspace = true }
wasm-timer = { workspace = true }

[dev-dependencies]
pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives-test-helpers = { workspace = true }
