[package]
name = "asset-hub-pezkuwichain-integration-tests"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Pezkuwichain runtime integration tests with xcm-emulator"
publish = false

[lints]
workspace = true

[dependencies]
assert_matches = { workspace = true }
codec = { workspace = true }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-asset-conversion = { workspace = true }
pallet-asset-rewards = { workspace = true }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
pallet-message-queue = { workspace = true }
pallet-treasury = { workspace = true }
pallet-utility = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

# Pezkuwi
pallet-xcm = { workspace = true }
pezkuwi-runtime-common = { workspace = true, default-features = true }
pezkuwichain-runtime-constants = { workspace = true, default-features = true }
xcm = { workspace = true }
xcm-executor = { workspace = true }
xcm-runtime-apis = { workspace = true, default-features = true }

# Cumulus
asset-test-utils = { workspace = true, default-features = true }
cumulus-pallet-teyrchain-system = { workspace = true }
emulated-integration-tests-common = { workspace = true }
pezkuwichain-system-emulated-network = { workspace = true }
teyrchains-common = { workspace = true, default-features = true }

[features]
runtime-benchmarks = [
	"asset-test-utils/runtime-benchmarks",
	"cumulus-pallet-teyrchain-system/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-rewards/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"pezkuwi-runtime-common/runtime-benchmarks",
	"pezkuwichain-runtime-constants/runtime-benchmarks",
	"pezkuwichain-system-emulated-network/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
