[package]
name = "pallet-trust-api"
version = "0.1.0"
description = "Runtime API for the Trust Pallet (from society group)"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
# External
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Substrate
sp-api = { default-features = false, path = "../../../../../primitives/api" }
sp-runtime = { default-features = false, path = "../../../../../primitives/runtime" }
sp-std = { default-features = false, path = "../../../../../primitives/std" }

# Pezkuwi
pezkuwi-primitives = { default-features = false, path = "../../../../../primitives/pezkuwi" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"pezkuwi-primitives/std",
]