[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "pezkuwi"

  [[relaychain.nodes]]
  name = "alice"
  args = ["-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "charlie"
  args = [ "-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "dave"
  args = [ "-lruntime=debug,parachain=trace" ]
