version: '3.8'

services:
  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: pezkuwi-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:10.0.0
    container_name: pezkuwi-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pezkuwi2024
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SECURE=false
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # Node Exporter - System metrics
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: pezkuwi-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # AlertManager - Alert handling
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: pezkuwi-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # Substrate Telemetry Backend
  telemetry-backend:
    image: parity/substrate-telemetry-backend:latest
    container_name: pezkuwi-telemetry-backend
    ports:
      - "8000:8000"
    environment:
      - TELEMETRY_URL=ws://0.0.0.0:8000/feed
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # Substrate Telemetry Frontend
  telemetry-frontend:
    image: parity/substrate-telemetry-frontend:latest
    container_name: pezkuwi-telemetry-frontend
    ports:
      - "8001:80"
    environment:
      - REACT_APP_SUBSTRATE_TELEMETRY_URL=ws://localhost:8000/feed
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

  # Jaeger - Distributed tracing (optional)
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: pezkuwi-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - pezkuwi-monitoring

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

networks:
  pezkuwi-monitoring:
    driver: bridge