[package]
name = "penpal-emulated-chain"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Penpal emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }

# Pezkuwi
xcm = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
penpal-runtime = { workspace = true }
teyrchains-common = { workspace = true, default-features = true }

[features]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks"
]
