[package]
name = "asset-hub-pezkuwichain-emulated-chain"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Asset Hub Pezkuwichain emulated chain"
publish = false
documentation = "https://docs.rs/asset-hub-pezkuwichain-emulated-chain"
repository = { workspace = true }
homepage = { workspace = true }

[lints]
workspace = true

[dependencies]
# Bizinikiwi
pezframe-support = { workspace = true }
pezsp-core = { workspace = true }
pezsp-keyring = { workspace = true }

# Pezcumulus
asset-hub-pezkuwichain-runtime = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
pezcumulus-primitives-core = { workspace = true }
pezkuwichain-emulated-chain = { workspace = true }
testnet-teyrchains-constants = { features = [
	"pezkuwichain",
], workspace = true, default-features = true }
teyrchains-common = { workspace = true, default-features = true }

# Pezkuwi
xcm = { workspace = true }
xcm-builder = { workspace = true, default-features = true }

# Bridges
bp-bridge-hub-pezkuwichain = { workspace = true }

[features]
runtime-benchmarks = [
	"asset-hub-pezkuwichain-runtime/runtime-benchmarks",
	"bp-bridge-hub-pezkuwichain/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"pezcumulus-primitives-core/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezkuwichain-emulated-chain/runtime-benchmarks",
	"pezsp-keyring/runtime-benchmarks",
	"testnet-teyrchains-constants/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
