
//! Autogenerated weights for `pallet_welati`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-11-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /home/mamostehp/Pezkuwi-SDK/target/release/pezkuwi
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_welati
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=./pallets/welati/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_welati`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `Welati::NextElectionId` (r:1 w:1)
	/// Proof: `Welati::NextElectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveElections` (r:0 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	fn initiate_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1489`
		// Minimum execution time: 11_611_000 picoseconds.
		Weight::from_parts(12_265_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn register_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `212`
		//  Estimated: `32819`
		// Minimum execution time: 20_501_000 picoseconds.
		Weight::from_parts(21_958_000, 0)
			.saturating_add(Weight::from_parts(0, 32819))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionVotes` (r:1 w:1)
	/// Proof: `Welati::ElectionVotes` (`max_values`: None, `max_size`: Some(435), added: 2910, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:1)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	fn cast_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1998`
		//  Estimated: `32819`
		// Minimum execution time: 28_120_000 picoseconds.
		Weight::from_parts(29_505_000, 0)
			.saturating_add(Weight::from_parts(0, 32819))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Welati::ActiveElections` (r:1 w:1)
	/// Proof: `Welati::ActiveElections` (`max_values`: None, `max_size`: Some(29354), added: 31829, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionCandidates` (r:1 w:0)
	/// Proof: `Welati::ElectionCandidates` (`max_values`: None, `max_size`: Some(3833), added: 6308, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ElectionResults` (r:0 w:1)
	/// Proof: `Welati::ElectionResults` (`max_values`: None, `max_size`: Some(6467), added: 8942, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:0 w:1)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn finalize_election() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2031`
		//  Estimated: `32819`
		// Minimum execution time: 26_310_000 picoseconds.
		Weight::from_parts(28_574_000, 0)
			.saturating_add(Weight::from_parts(0, 32819))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentMinisters` (r:1 w:0)
	/// Proof: `Welati::CurrentMinisters` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:1 w:0)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextAppointmentId` (r:1 w:1)
	/// Proof: `Welati::NextAppointmentId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:0 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	fn nominate_official() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `3638`
		// Minimum execution time: 24_977_000 picoseconds.
		Weight::from_parts(26_238_000, 0)
			.saturating_add(Weight::from_parts(0, 3638))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointmentProcesses` (r:1 w:1)
	/// Proof: `Welati::AppointmentProcesses` (`max_values`: None, `max_size`: Some(10119), added: 12594, mode: `MaxEncodedLen`)
	/// Storage: `Welati::PendingNominations` (r:1 w:1)
	/// Proof: `Welati::PendingNominations` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AppointedOfficials` (r:0 w:1)
	/// Proof: `Welati::AppointedOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn approve_appointment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `511`
		//  Estimated: `13584`
		// Minimum execution time: 26_390_000 picoseconds.
		Weight::from_parts(27_599_000, 0)
			.saturating_add(Weight::from_parts(0, 13584))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CurrentOfficials` (r:1 w:0)
	/// Proof: `Welati::CurrentOfficials` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Welati::NextProposalId` (r:1 w:1)
	/// Proof: `Welati::NextProposalId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ActiveProposals` (r:0 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `186`
		//  Estimated: `12542`
		// Minimum execution time: 17_560_000 picoseconds.
		Weight::from_parts(18_168_000, 0)
			.saturating_add(Weight::from_parts(0, 12542))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Welati::ActiveProposals` (r:1 w:1)
	/// Proof: `Welati::ActiveProposals` (`max_values`: None, `max_size`: Some(1195), added: 3670, mode: `MaxEncodedLen`)
	/// Storage: `Welati::CollectiveVotes` (r:1 w:1)
	/// Proof: `Welati::CollectiveVotes` (`max_values`: None, `max_size`: Some(612), added: 3087, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	fn vote_on_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `12542`
		// Minimum execution time: 22_421_000 picoseconds.
		Weight::from_parts(23_225_000, 0)
			.saturating_add(Weight::from_parts(0, 12542))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
