[package]
name = "pezstaging-xcm-builder"
description = "Tools & types for building with XCM and its executor."
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "7.0.0"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
environmental = { workspace = true }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
impl-trait-for-tuples = { workspace = true }
pezpallet-asset-conversion = { workspace = true }
pezpallet-transaction-payment = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
pezsp-arithmetic = { workspace = true }
pezsp-core = { workspace = true }
pezsp-io = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-weights = { workspace = true }
tracing = { workspace = true }
xcm = { workspace = true }
xcm-executor = { workspace = true }

# Pezkuwi dependencies
pezkuwi-teyrchain-primitives = { workspace = true }

[dev-dependencies]
pezpallet-assets = { workspace = true, default-features = true }
pezpallet-balances = { workspace = true, default-features = true }
pezpallet-salary = { workspace = true, default-features = true }
pezpallet-xcm = { workspace = true, default-features = true }
pezkuwi-primitives = { workspace = true, default-features = true }
pezkuwi-runtime-teyrchains = { workspace = true, default-features = true }
pezkuwi-test-runtime = { workspace = true }
primitive-types = { features = [
	"codec",
	"num-traits",
	"scale-info",
], workspace = true }
pezsp-tracing = { workspace = true, default-features = true }
xcm-simulator = { workspace = true, default-features = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezpallet-asset-conversion/runtime-benchmarks",
	"pezpallet-assets/runtime-benchmarks",
	"pezpallet-balances/runtime-benchmarks",
	"pezpallet-salary/runtime-benchmarks",
	"pezpallet-transaction-payment/runtime-benchmarks",
	"pezpallet-xcm/runtime-benchmarks",
	"pezkuwi-primitives/runtime-benchmarks",
	"pezkuwi-runtime-teyrchains/runtime-benchmarks",
	"pezkuwi-test-runtime/runtime-benchmarks",
	"pezkuwi-teyrchain-primitives/runtime-benchmarks",
	"pezsp-io/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm-simulator/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
std = [
	"codec/std",
	"environmental/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezpallet-asset-conversion/std",
	"pezpallet-transaction-payment/std",
	"pezkuwi-teyrchain-primitives/std",
	"primitive-types/std",
	"scale-info/std",
	"pezsp-arithmetic/std",
	"pezsp-core/std",
	"pezsp-io/std",
	"pezsp-runtime/std",
	"pezsp-weights/std",
	"tracing/std",
	"xcm-executor/std",
	"xcm/std",
]
