- job-name: "zombienet-teyrchain-template-0001-minimal_template_block_production"
  test-filter: "smoke::minimal_template_block_production_test"
  runner-type: "default"
  pezcumulus-image: "test-teyrchain"
  use-zombienet-sdk: true

- job-name: "zombienet-teyrchain-template-0002-teyrchain_template_block_production"
  test-filter: "smoke::teyrchain_template_block_production_test"
  runner-type: "default"
  pezcumulus-image: "test-teyrchain"
  use-zombienet-sdk: true

- job-name: "zombienet-teyrchain-template-0003-solochain_template_block_production"
  test-filter: "smoke::solochain_template_block_production_test"
  runner-type: "default"
  pezcumulus-image: "test-teyrchain"
  use-zombienet-sdk: true
