[package]
name = "pezkuwi-gossip-support"
version = "22.0.0"
description = "Pezkuwi Gossip Support subsystem. Responsible for keeping track of session changes and issuing a connection request to the relevant validators on every new session."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
pezkuwi-node-network-protocol.default-features = true
pezkuwi-node-network-protocol.workspace = true
pezkuwi-node-subsystem-util.default-features = true
pezkuwi-node-subsystem-util.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
sc-network.default-features = true
sc-network.workspace = true
sp-application-crypto.default-features = true
sp-application-crypto.workspace = true
sp-core.default-features = true
sp-core.workspace = true
sp-crypto-hashing.default-features = true
sp-crypto-hashing.workspace = true
sp-keystore.default-features = true
sp-keystore.workspace = true

futures = { workspace = true }
futures-timer = { workspace = true }
gum.default-features = true
gum.workspace = true
rand = { workspace = true }
rand_chacha = { workspace = true }

[dev-dependencies]
sp-authority-discovery = { default-features = true, workspace = true }
sp-consensus-babe = { default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }
sp-tracing = { default-features = true, workspace = true }

pezkuwi-node-subsystem-test-helpers = { workspace = true }

assert_matches = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true, default-features = true }
quickcheck = { workspace = true, default-features = true }
