[book]
authors = [
	"Kurdistan Tech Institute <info@pezkuwichain.io>",
	"Parity Technologies <admin@parity.io>",
]
language = "en"
multilingual = false
src = "src"
title = "The Pezkuwi Teyrchain Host Implementers' Guide"

[preprocessor.graphviz]
command = "mdbook-graphviz"
optional = true
[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true
[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]
optional = true

[output.html]
additional-css = ["last-changed.css"]
additional-js = ["mermaid-init.js", "mermaid.min.js"]
# Repository URL used in the last-changed link.
git-repository-url = "https://github.com/pezkuwichain/pezkuwi-sdk"

[output.linkcheck]
optional = true
