[package]
name = "pez-chain-spec-guide-runtime"
description = "A minimal runtime for chain spec guide"
version = "0.0.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
documentation = "https://docs.rs/pez-chain-spec-guide-runtime"

[dependencies]
codec = { workspace = true }
docify = { workspace = true }
pezframe-support = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# this is a frame-based runtime, thus importing `frame` with runtime feature enabled.
frame = { features = ["experimental", "runtime"], workspace = true }

# genesis builder that allows us to interact with runtime genesis config
pezsp-application-crypto = { features = ["serde"], workspace = true }
pezsp-core = { workspace = true }
pezsp-genesis-builder = { workspace = true }
pezsp-keyring = { workspace = true }
pezsp-runtime = { features = ["serde"], workspace = true }

[dev-dependencies]
cmd_lib = { workspace = true }
pezsc-chain-spec = { workspace = true, default-features = true }

[build-dependencies]
bizinikiwi-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",

	"frame/std",
	"pezframe-support/std",

	"pezsp-application-crypto/std",
	"pezsp-core/std",
	"pezsp-genesis-builder/std",
	"pezsp-keyring/std",
	"pezsp-runtime/std",

	"bizinikiwi-wasm-builder",
	"serde/std",
	"serde_json/std",
]
runtime-benchmarks = [
	"bizinikiwi-wasm-builder?/runtime-benchmarks",
	"frame/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezsc-chain-spec/runtime-benchmarks",
	"pezsp-genesis-builder/runtime-benchmarks",
	"pezsp-keyring/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
