[package]
name = "pezbridge-hub-pezkuwichain-integration-tests"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Pezkuwichain runtime integration tests with xcm-pez-emulator"
publish = false
documentation.workspace = true
repository = { workspace = true }
homepage = { workspace = true }

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
hex-literal = { workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }

# Bizinikiwi
pezframe-support = { workspace = true }
pezpallet-asset-conversion = { workspace = true }
pezpallet-assets = { workspace = true }
pezpallet-balances = { workspace = true }
pezpallet-message-queue = { workspace = true, default-features = true }
pezsp-core = { workspace = true }
pezsp-runtime = { workspace = true }

# Pezkuwi
pezpallet-xcm = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }

# Bridges
bp-asset-hub-pezkuwichain = { workspace = true }
pezpallet-bridge-messages = { workspace = true }

# Pezcumulus
asset-hub-pezkuwichain-runtime = { workspace = true }
emulated-integration-tests-common = { workspace = true }
pezcumulus-pezpallet-xcmp-queue = { workspace = true }
pezkuwichain-system-emulated-network = { workspace = true }
pezkuwichain-zagros-system-emulated-network = { workspace = true }
testnet-teyrchains-constants = { features = [
	"pezkuwichain",
	"zagros",
], workspace = true, default-features = true }
teyrchains-common = { workspace = true, default-features = true }

# Snowbridge
pezsnowbridge-inbound-queue-primitives = { workspace = true }
pezsnowbridge-outbound-queue-primitives = { workspace = true }
pezsnowbridge-pezpallet-inbound-queue-fixtures = { workspace = true, default-features = true }
pezsnowbridge-pezpallet-outbound-queue = { workspace = true }
pezsnowbridge-pezpallet-system = { workspace = true }

[features]
runtime-benchmarks = [
	"asset-hub-pezkuwichain-runtime/runtime-benchmarks",
	"bp-asset-hub-pezkuwichain/runtime-benchmarks",
	"emulated-integration-tests-common/runtime-benchmarks",
	"pezcumulus-pezpallet-xcmp-queue/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezkuwichain-system-emulated-network/runtime-benchmarks",
	"pezkuwichain-zagros-system-emulated-network/runtime-benchmarks",
	"pezpallet-asset-conversion/runtime-benchmarks",
	"pezpallet-assets/runtime-benchmarks",
	"pezpallet-balances/runtime-benchmarks",
	"pezpallet-bridge-messages/runtime-benchmarks",
	"pezpallet-message-queue/runtime-benchmarks",
	"pezpallet-xcm/runtime-benchmarks",
	"pezsnowbridge-inbound-queue-primitives/runtime-benchmarks",
	"pezsnowbridge-outbound-queue-primitives/runtime-benchmarks",
	"pezsnowbridge-pezpallet-inbound-queue-fixtures/runtime-benchmarks",
	"pezsnowbridge-pezpallet-outbound-queue/runtime-benchmarks",
	"pezsnowbridge-pezpallet-system/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"testnet-teyrchains-constants/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
