[package]
name = "bp-bridge-hub-pezcumulus"
description = "Primitives for BridgeHub teyrchain runtimes."
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
documentation = "https://docs.rs/bp-bridge-hub-pezcumulus"
homepage = { workspace = true }

[package.metadata.pezkuwi-sdk]
exclude-from-umbrella = true

[lints]
workspace = true

[dependencies]
# Bridge Dependencies
bp-messages = { workspace = true }
bp-pezkuwi-core = { workspace = true }
bp-runtime = { workspace = true }

# Bizinikiwi Based Dependencies
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
pezsp-api = { workspace = true }
pezsp-std = { workspace = true }
teyrchains-common = { workspace = true }

# Pezkuwi Dependencies
pezkuwi-primitives = { workspace = true }

[features]
default = ["std"]
std = [
  "bp-messages/std",
  "bp-pezkuwi-core/std",
  "bp-runtime/std",
  "pezframe-support/std",
  "pezframe-system/std",
  "pezkuwi-primitives/std",
  "pezsp-api/std",
  "pezsp-std/std",
  "teyrchains-common/std",
]
runtime-benchmarks = [
  "bp-messages/runtime-benchmarks",
  "bp-pezkuwi-core/runtime-benchmarks",
  "bp-runtime/runtime-benchmarks",
  "pezframe-support/runtime-benchmarks",
  "pezframe-system/runtime-benchmarks",
  "pezkuwi-primitives/runtime-benchmarks",
  "pezsp-api/runtime-benchmarks",
  "teyrchains-common/runtime-benchmarks",
]
