// This file is part of Bizinikiwi.

// Copyright (C) Parity Technologies (UK) Ltd. and Dijital Kurdistan Tech Institute
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pezpallet_validator_pool`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE BIZINIKIWI BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-11-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /home/mamostehp/Pezkuwi-SDK/target/release/pezkuwi
// benchmark
// pezpallet
// --chain=dev
// --pezpallet=pezpallet_validator_pool
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=/home/mamostehp/Pezkuwi-SDK/pezkuwi/pallets/validator-pool/src/weights.rs
// --template=/home/mamostehp/Pezkuwi-SDK/bizinikiwi/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use pezframe_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::WeightInfo;

/// Weights for `pezpallet_validator_pool` using the Bizinikiwi node and recommended hardware.
pub struct BizinikiwiWeight<T>(PhantomData<T>);
impl<T: pezframe_system::Config> WeightInfo for BizinikiwiWeight<T> {
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolSize` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:0)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:0 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn join_validator_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110`
		//  Estimated: `3546`
		// Minimum execution time: 16_865_000 picoseconds.
		Weight::from_parts(18_041_000, 3546)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolSize` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:0 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::SelectionHistory` (r:0 w:1)
	/// Proof: `ValidatorPool::SelectionHistory` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn leave_validator_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3546`
		// Minimum execution time: 18_228_000 picoseconds.
		Weight::from_parts(18_832_000, 3546)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:1 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:0)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_performance_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3530`
		// Minimum execution time: 15_814_000 picoseconds.
		Weight::from_parts(16_553_000, 3530)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:1)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Babe::NextRandomness` (r:1 w:0)
	/// Proof: `Babe::NextRandomness` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Babe::EpochStart` (r:1 w:0)
	/// Proof: `Babe::EpochStart` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolMembers` (r:101 w:0)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::SelectionHistory` (r:100 w:21)
	/// Proof: `ValidatorPool::SelectionHistory` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:100 w:0)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentValidatorSet` (r:0 w:1)
	/// Proof: `ValidatorPool::CurrentValidatorSet` (`max_values`: Some(1), `max_size`: Some(679), added: 1174, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::EraStart` (r:0 w:1)
	/// Proof: `ValidatorPool::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[4, 100]`.
	fn force_new_era(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354 + p * (139 ±0)`
		//  Estimated: `3546 + p * (2556 ±0)`
		// Minimum execution time: 68_990_000 picoseconds.
		Weight::from_parts(55_692_892, 3546)
			// Standard Error: 19_014
			.saturating_add(Weight::from_parts(9_817_847, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(17_u64))
			.saturating_add(Weight::from_parts(0, 2556).saturating_mul(p.into()))
	}
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn update_category() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3546`
		// Minimum execution time: 15_344_000 picoseconds.
		Weight::from_parts(16_181_000, 3546)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorPool::EraLength` (r:0 w:1)
	/// Proof: `ValidatorPool::EraLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_pool_parameters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_159_000 picoseconds.
		Weight::from_parts(6_422_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolSize` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:0)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:0 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	fn join_validator_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `110`
		//  Estimated: `3546`
		// Minimum execution time: 16_865_000 picoseconds.
		Weight::from_parts(18_041_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolSize` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:0 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::SelectionHistory` (r:0 w:1)
	/// Proof: `ValidatorPool::SelectionHistory` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn leave_validator_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `267`
		//  Estimated: `3546`
		// Minimum execution time: 18_228_000 picoseconds.
		Weight::from_parts(18_832_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:1 w:1)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:0)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_performance_metrics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3530`
		// Minimum execution time: 15_814_000 picoseconds.
		Weight::from_parts(16_553_000, 3530)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorPool::CurrentEra` (r:1 w:1)
	/// Proof: `ValidatorPool::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Babe::NextRandomness` (r:1 w:0)
	/// Proof: `Babe::NextRandomness` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Babe::EpochStart` (r:1 w:0)
	/// Proof: `Babe::EpochStart` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PoolMembers` (r:101 w:0)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::SelectionHistory` (r:100 w:21)
	/// Proof: `ValidatorPool::SelectionHistory` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::PerformanceMetrics` (r:100 w:0)
	/// Proof: `ValidatorPool::PerformanceMetrics` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::CurrentValidatorSet` (r:0 w:1)
	/// Proof: `ValidatorPool::CurrentValidatorSet` (`max_values`: Some(1), `max_size`: Some(679), added: 1174, mode: `MaxEncodedLen`)
	/// Storage: `ValidatorPool::EraStart` (r:0 w:1)
	/// Proof: `ValidatorPool::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[4, 100]`.
	fn force_new_era(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354 + p * (139 ±0)`
		//  Estimated: `3546 + p * (2556 ±0)`
		// Minimum execution time: 68_990_000 picoseconds.
		Weight::from_parts(55_692_892, 3546)
			// Standard Error: 19_014
			.saturating_add(Weight::from_parts(9_817_847, 0).saturating_mul(p.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(p.into())))
			.saturating_add(RocksDbWeight::get().writes(17_u64))
			.saturating_add(Weight::from_parts(0, 2556).saturating_mul(p.into()))
	}
	/// Storage: `ValidatorPool::PoolMembers` (r:1 w:1)
	/// Proof: `ValidatorPool::PoolMembers` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	fn update_category() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3546`
		// Minimum execution time: 15_344_000 picoseconds.
		Weight::from_parts(16_181_000, 3546)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorPool::EraLength` (r:0 w:1)
	/// Proof: `ValidatorPool::EraLength` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_pool_parameters() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_159_000 picoseconds.
		Weight::from_parts(6_422_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
