[package]
name = "people-zagros-integration-tests"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "People Zagros runtime integration tests with xcm-emulator"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true }

# Substrate
frame-support = { workspace = true }
pallet-balances = { workspace = true }
pallet-identity = { workspace = true }
pallet-message-queue = { workspace = true }
pallet-xcm = { workspace = true }
sp-runtime = { workspace = true }

# Pezkuwi
xcm = { workspace = true }
xcm-executor = { workspace = true }
zagros-runtime = { workspace = true }

# Cumulus
emulated-integration-tests-common = { workspace = true }
teyrchains-common = { workspace = true, default-features = true }
zagros-system-emulated-network = { workspace = true }

[features]
runtime-benchmarks = [
	"emulated-integration-tests-common/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"teyrchains-common/runtime-benchmarks",
	"zagros-runtime/runtime-benchmarks",
	"zagros-system-emulated-network/runtime-benchmarks"
]
