[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "1.0.0"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = true }
frame-support = { workspace = true }
frame-system = { workspace = true, default-features = true }
futures = { workspace = true }
pallet-sudo = { workspace = true, default-features = true }
pallet-transaction-payment = { workspace = true, default-features = true }
pallet-xcm = { workspace = true, default-features = true }
pezkuwi-runtime-teyrchains = { workspace = true, default-features = true }
pezkuwi-test-client = { workspace = true }
pezkuwi-test-runtime = { workspace = true }
pezkuwi-test-service = { workspace = true }
sp-consensus = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }
xcm = { workspace = true }
xcm-executor = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-sudo/std",
	"pezkuwi-runtime-teyrchains/std",
	"sp-runtime/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"pezkuwi-runtime-teyrchains/runtime-benchmarks",
	"pezkuwi-test-client/runtime-benchmarks",
	"pezkuwi-test-runtime/runtime-benchmarks",
	"pezkuwi-test-service/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-state-machine/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
