[package]
name = "test-parachain-undying-collator"
description = "Collator for the undying test parachain"
edition.workspace = true
license.workspace = true
version = "1.0.0"
authors.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "undying-collator"
path = "src/main.rs"

[dependencies]
clap = { features = ["derive"], workspace = true }
codec = { features = ["derive"], workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
pezkuwi-cli.default-features = true
pezkuwi-cli.workspace = true
pezkuwi-erasure-coding.default-features = true
pezkuwi-erasure-coding.workspace = true
pezkuwi-node-primitives.default-features = true
pezkuwi-node-primitives.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
pezkuwi-service = { features = ["rococo-native"], workspace = true, default-features = true }
sc-cli.default-features = true
sc-cli.workspace = true
sc-client-api.default-features = true
sc-client-api.workspace = true
sc-service.default-features = true
sc-service.workspace = true
sp-core.default-features = true
sp-core.workspace = true
test-parachain-undying.workspace = true

[dev-dependencies]
pezkuwi-node-core-pvf = { features = ["test-utils"], default-features = true, workspace = true }
pezkuwi-parachain-primitives = { default-features = true, workspace = true }
pezkuwi-test-service = { workspace = true }

sc-service = { default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }

tokio = { features = ["macros"], workspace = true, default-features = true }
