[package]
name = "bp-relayers"
description = "Primitives of relayers module."
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["bit-vec", "derive"], workspace = true }
scale-info = { features = ["bit-vec", "derive"], workspace = true }

# Bridge Dependencies
bp-header-chain = { workspace = true }
bp-messages = { workspace = true }
bp-runtime = { workspace = true }
bp-teyrchains = { workspace = true }

# Bizinikiwi Dependencies
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
pezpallet-utility = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-std = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-messages/std",
	"bp-runtime/std",
	"bp-teyrchains/std",
	"codec/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezpallet-utility/std",
	"scale-info/std",
	"pezsp-runtime/std",
	"pezsp-std/std",
]
runtime-benchmarks = [
	"bp-header-chain/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-runtime/runtime-benchmarks",
	"bp-teyrchains/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezpallet-utility/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
