[package]
name = "pezkuwi-availability-bitfield-distribution"
version = "22.0.0"
description = "Pezkuwi Bitfiled Distribution subsystem, which gossips signed availability bitfields used to compactly determine which backed candidates are available or not based on a 2/3+ quorum."
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
gum.default-features = true
gum.workspace = true
pezkuwi-node-network-protocol.default-features = true
pezkuwi-node-network-protocol.workspace = true
pezkuwi-node-subsystem-util.default-features = true
pezkuwi-node-subsystem-util.workspace = true
pezkuwi-node-subsystem.default-features = true
pezkuwi-node-subsystem.workspace = true
pezkuwi-primitives.default-features = true
pezkuwi-primitives.workspace = true
rand = { workspace = true, default-features = true }

[dev-dependencies]
assert_matches = { workspace = true }
bitvec = { features = ["alloc"], workspace = true }
maplit = { workspace = true }
pezkuwi-node-subsystem-test-helpers = { workspace = true }
rand_chacha = { workspace = true, default-features = true }
sp-application-crypto = { default-features = true, workspace = true }
sp-authority-discovery = { default-features = true, workspace = true }
sp-core = { default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }
sp-keystore = { default-features = true, workspace = true }
sp-tracing = { default-features = false, workspace = true }
