[package]
name = "bp-zagros"
description = "Primitives of Zagros runtime."
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
documentation = "https://docs.rs/bp-zagros"
homepage = { workspace = true }

[package.metadata.pezkuwi-sdk]
exclude-from-umbrella = true

[lints]
workspace = true

[dependencies]
# Bridge Dependencies
bp-header-chain = { workspace = true }
bp-pezkuwi-core = { workspace = true }
bp-runtime = { workspace = true }

# Bizinikiwi Based Dependencies
pezframe-support = { workspace = true }
pezsp-api = { workspace = true }
pezsp-std = { workspace = true }

[features]
default = ["std"]
std = [
  "bp-header-chain/std",
  "bp-pezkuwi-core/std",
  "bp-runtime/std",
  "pezframe-support/std",
  "pezsp-api/std",
  "pezsp-std/std",
]
runtime-benchmarks = [
  "bp-header-chain/runtime-benchmarks",
  "bp-pezkuwi-core/runtime-benchmarks",
  "bp-runtime/runtime-benchmarks",
  "pezframe-support/runtime-benchmarks",
  "pezsp-api/runtime-benchmarks",
]
