[package]
name = "cumulus-pov-validator"
version = "0.5.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
description = "A tool for validating PoVs locally"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
codec.workspace = true
pezkuwi-node-primitives.workspace = true
pezkuwi-parachain-primitives.workspace = true
pezkuwi-primitives.workspace = true
sc-executor.workspace = true
sp-core.workspace = true
sp-io.workspace = true
sp-maybe-compressed-blob.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[lints]
workspace = true
