[package]
name = "frame-storage-access-test-runtime"
description = "A runtime for testing storage access on block validation"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
publish = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
pezcumulus-pezpallet-teyrchain-system = { workspace = true, optional = true }
pezsp-core = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-state-machine = { workspace = true }
pezsp-trie = { workspace = true }

[build-dependencies]
bizinikiwi-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"pezcumulus-pezpallet-teyrchain-system/std",
	"pezsp-core/std",
	"pezsp-runtime/std",
	"pezsp-state-machine/std",
	"pezsp-trie/std",
	"bizinikiwi-wasm-builder",
]
runtime-benchmarks = [
	"pezcumulus-pezpallet-teyrchain-system/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"pezsp-state-machine/runtime-benchmarks",
	"pezsp-trie/runtime-benchmarks",
	"bizinikiwi-wasm-builder?/runtime-benchmarks",
]
