[package]
name = "pezkuwi-service"
rust-version = "1.60"
version = "7.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Utils to tie different Pezkuwi components together and allow instantiation of a node."
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Substrate Client
mmr-gadget = { workspace = true, default-features = true }
sc-authority-discovery = { workspace = true, default-features = true }
sc-basic-authorship = { workspace = true, default-features = true }
sc-chain-spec = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sc-consensus = { workspace = true, default-features = true }
sc-consensus-babe = { workspace = true, default-features = true }
sc-consensus-beefy = { workspace = true, default-features = true }
sc-consensus-grandpa = { workspace = true, default-features = true }
sc-consensus-slots = { workspace = true, default-features = true }
sc-executor = { workspace = true, default-features = true }
sc-keystore = { workspace = true, default-features = true }
sc-network = { workspace = true, default-features = true }
sc-network-sync = { workspace = true, default-features = true }
sc-offchain = { workspace = true, default-features = true }
sc-service = { workspace = true }
sc-sync-state-rpc = { workspace = true, default-features = true }
sc-sysinfo = { workspace = true, default-features = true }
sc-telemetry = { workspace = true, default-features = true }
sc-transaction-pool = { workspace = true, default-features = true }
sc-transaction-pool-api = { workspace = true, default-features = true }
sp-genesis-builder = { workspace = true, default-features = true }
sp-mmr-primitives = { workspace = true, default-features = true }

# Substrate Primitives
pallet-transaction-payment = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-authority-discovery = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-consensus = { workspace = true, default-features = true }
sp-consensus-babe = { workspace = true, default-features = true }
sp-consensus-beefy = { workspace = true, default-features = true }
sp-consensus-grandpa = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-inherents = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-offchain = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-session = { workspace = true, default-features = true }
sp-timestamp = { workspace = true, default-features = true }
sp-transaction-pool = { workspace = true, default-features = true }
sp-version = { workspace = true, default-features = true }
sp-weights = { workspace = true, default-features = true }

# Substrate Pallets
frame-metadata-hash-extension = { optional = true, workspace = true, default-features = true }
frame-system = { workspace = true, default-features = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = true }

# Substrate Other
frame-benchmarking = { workspace = true, default-features = true }
frame-benchmarking-cli = { workspace = true, default-features = true }
frame-system-rpc-runtime-api = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }

# External Crates
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
gum = { workspace = true, default-features = true }
is_executable = { workspace = true }
kvdb = { workspace = true }
kvdb-rocksdb = { optional = true, workspace = true }
log = { workspace = true, default-features = true }
parity-db = { optional = true, workspace = true }
parking_lot = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }

# Pezkuwi
pezkuwi-core-primitives = { workspace = true, default-features = true }
pezkuwi-node-core-teyrchains-inherent = { workspace = true, default-features = true }
pezkuwi-node-network-protocol = { workspace = true, default-features = true }
pezkuwi-node-primitives = { workspace = true, default-features = true }
pezkuwi-node-subsystem = { workspace = true, default-features = true }
pezkuwi-node-subsystem-types = { workspace = true, default-features = true }
pezkuwi-node-subsystem-util = { workspace = true, default-features = true }
pezkuwi-overseer = { workspace = true, default-features = true }
pezkuwi-primitives = { workspace = true, default-features = true }
pezkuwi-rpc = { workspace = true, default-features = true }
pezkuwi-runtime-teyrchains = { workspace = true, default-features = true }

# Pezkuwi Runtime Constants
pezkuwichain-runtime-constants = { optional = true, workspace = true, default-features = true }
zagros-runtime-constants = { optional = true, workspace = true, default-features = true }

# Pezkuwi Runtimes
pezkuwichain-runtime = { optional = true, workspace = true }
zagros-runtime = { optional = true, workspace = true, default-features = true }

# Pezkuwi Subsystems
pezkuwi-approval-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-bitfield-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-recovery = { optional = true, workspace = true, default-features = true }
pezkuwi-collator-protocol = { optional = true, workspace = true, default-features = true }
pezkuwi-dispute-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-gossip-support = { optional = true, workspace = true, default-features = true }
pezkuwi-network-bridge = { optional = true, workspace = true, default-features = true }
pezkuwi-node-collation-generation = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-approval-voting = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-approval-voting-parallel = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-av-store = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-backing = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-bitfield-signing = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-candidate-validation = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-chain-api = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-chain-selection = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-dispute-coordinator = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-prospective-teyrchains = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-provisioner = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-pvf = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-pvf-checker = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-runtime-api = { optional = true, workspace = true, default-features = true }
pezkuwi-statement-distribution = { optional = true, workspace = true, default-features = true }

xcm = { workspace = true, default-features = true }
xcm-runtime-apis = { workspace = true, default-features = true }

[dev-dependencies]
assert_matches = { workspace = true }
pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives-test-helpers = { workspace = true }
pezkuwi-test-client = { workspace = true }
sp-tracing = { workspace = true }
tempfile = { workspace = true }

[features]
default = ["db", "full-node"]
db = ["sc-service/rocksdb"]
full-node = [
	"kvdb-rocksdb",
	"parity-db",
	"pezkuwi-approval-distribution",
	"pezkuwi-availability-bitfield-distribution",
	"pezkuwi-availability-distribution",
	"pezkuwi-availability-recovery",
	"pezkuwi-collator-protocol",
	"pezkuwi-dispute-distribution",
	"pezkuwi-gossip-support",
	"pezkuwi-network-bridge",
	"pezkuwi-node-collation-generation",
	"pezkuwi-node-core-approval-voting",
	"pezkuwi-node-core-approval-voting-parallel",
	"pezkuwi-node-core-av-store",
	"pezkuwi-node-core-backing",
	"pezkuwi-node-core-bitfield-signing",
	"pezkuwi-node-core-candidate-validation",
	"pezkuwi-node-core-chain-api",
	"pezkuwi-node-core-chain-selection",
	"pezkuwi-node-core-dispute-coordinator",
	"pezkuwi-node-core-prospective-teyrchains",
	"pezkuwi-node-core-provisioner",
	"pezkuwi-node-core-pvf",
	"pezkuwi-node-core-pvf-checker",
	"pezkuwi-node-core-runtime-api",
	"pezkuwi-statement-distribution",
]

# Configure the native runtimes to use.
zagros-native = [
	"frame-metadata-hash-extension",
	"zagros-runtime",
	"zagros-runtime-constants",
]
pezkuwichain-native = [
	"frame-metadata-hash-extension",
	"pezkuwichain-runtime",
	"pezkuwichain-runtime-constants",
]

# Generate the metadata hash needed for CheckMetadataHash
# in the test runtimes.
metadata-hash = [
	"pezkuwichain-runtime?/metadata-hash",
	"zagros-runtime?/metadata-hash",
]

runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"pezkuwi-primitives/runtime-benchmarks",
	"pezkuwi-runtime-teyrchains/runtime-benchmarks",
	"pezkuwi-test-client/runtime-benchmarks",
	"pezkuwichain-runtime?/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"zagros-runtime-constants?/runtime-benchmarks",
	"zagros-runtime?/runtime-benchmarks",
	"frame-metadata-hash-extension?/runtime-benchmarks",
	"mmr-gadget/runtime-benchmarks",
	"pallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"pezkuwi-approval-distribution?/runtime-benchmarks",
	"pezkuwi-availability-bitfield-distribution?/runtime-benchmarks",
	"pezkuwi-availability-distribution?/runtime-benchmarks",
	"pezkuwi-availability-recovery?/runtime-benchmarks",
	"pezkuwi-collator-protocol?/runtime-benchmarks",
	"pezkuwi-core-primitives/runtime-benchmarks",
	"pezkuwi-dispute-distribution?/runtime-benchmarks",
	"pezkuwi-gossip-support?/runtime-benchmarks",
	"pezkuwi-network-bridge?/runtime-benchmarks",
	"pezkuwi-node-collation-generation?/runtime-benchmarks",
	"pezkuwi-node-core-approval-voting?/runtime-benchmarks",
	"pezkuwi-node-core-approval-voting-parallel?/runtime-benchmarks",
	"pezkuwi-node-core-av-store?/runtime-benchmarks",
	"pezkuwi-node-core-backing?/runtime-benchmarks",
	"pezkuwi-node-core-bitfield-signing?/runtime-benchmarks",
	"pezkuwi-node-core-candidate-validation?/runtime-benchmarks",
	"pezkuwi-node-core-chain-api?/runtime-benchmarks",
	"pezkuwi-node-core-chain-selection?/runtime-benchmarks",
	"pezkuwi-node-core-dispute-coordinator?/runtime-benchmarks",
	"pezkuwi-node-core-prospective-teyrchains?/runtime-benchmarks",
	"pezkuwi-node-core-provisioner?/runtime-benchmarks",
	"pezkuwi-node-core-pvf?/runtime-benchmarks",
	"pezkuwi-node-core-pvf-checker?/runtime-benchmarks",
	"pezkuwi-node-core-runtime-api?/runtime-benchmarks",
	"pezkuwi-node-core-teyrchains-inherent/runtime-benchmarks",
	"pezkuwi-node-network-protocol/runtime-benchmarks",
	"pezkuwi-node-primitives/runtime-benchmarks",
	"pezkuwi-node-subsystem-test-helpers/runtime-benchmarks",
	"pezkuwi-node-subsystem-types/runtime-benchmarks",
	"pezkuwi-node-subsystem-util/runtime-benchmarks",
	"pezkuwi-overseer/runtime-benchmarks",
	"pezkuwi-primitives-test-helpers/runtime-benchmarks",
	"pezkuwi-rpc/runtime-benchmarks",
	"pezkuwi-statement-distribution?/runtime-benchmarks",
	"pezkuwichain-runtime-constants?/runtime-benchmarks",
	"sc-authority-discovery/runtime-benchmarks",
	"sc-basic-authorship/runtime-benchmarks",
	"sc-chain-spec/runtime-benchmarks",
	"sc-client-api/runtime-benchmarks",
	"sc-consensus/runtime-benchmarks",
	"sc-consensus-babe/runtime-benchmarks",
	"sc-consensus-beefy/runtime-benchmarks",
	"sc-consensus-grandpa/runtime-benchmarks",
	"sc-consensus-slots/runtime-benchmarks",
	"sc-executor/runtime-benchmarks",
	"sc-network/runtime-benchmarks",
	"sc-network-sync/runtime-benchmarks",
	"sc-offchain/runtime-benchmarks",
	"sc-sync-state-rpc/runtime-benchmarks",
	"sc-sysinfo/runtime-benchmarks",
	"sc-transaction-pool/runtime-benchmarks",
	"sc-transaction-pool-api/runtime-benchmarks",
	"sp-api/runtime-benchmarks",
	"sp-authority-discovery/runtime-benchmarks",
	"sp-block-builder/runtime-benchmarks",
	"sp-blockchain/runtime-benchmarks",
	"sp-consensus/runtime-benchmarks",
	"sp-consensus-babe/runtime-benchmarks",
	"sp-consensus-beefy/runtime-benchmarks",
	"sp-consensus-grandpa/runtime-benchmarks",
	"sp-genesis-builder/runtime-benchmarks",
	"sp-inherents/runtime-benchmarks",
	"sp-keyring/runtime-benchmarks",
	"sp-mmr-primitives/runtime-benchmarks",
	"sp-offchain/runtime-benchmarks",
	"sp-session/runtime-benchmarks",
	"sp-timestamp/runtime-benchmarks",
	"sp-transaction-pool/runtime-benchmarks",
	"sp-version/runtime-benchmarks",
	"gum/runtime-benchmarks"
]
try-runtime = [
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pezkuwi-runtime-teyrchains/try-runtime",
	"pezkuwichain-runtime?/try-runtime",
	"sp-runtime/try-runtime",
	"zagros-runtime?/try-runtime",
]
fast-runtime = [
	"pezkuwichain-runtime?/fast-runtime",
	"zagros-runtime?/fast-runtime",
]

malus = ["full-node"]
runtime-metrics = [
	"pezkuwi-runtime-teyrchains/runtime-metrics",
	"pezkuwichain-runtime?/runtime-metrics",
	"zagros-runtime?/runtime-metrics",
]
