[package]
name = "pezkuwi-service"
rust-version = "1.60"
version = "7.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Utils to tie different Pezkuwi components together and allow instantiation of a node."
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Bizinikiwi Client
mmr-gadget = { workspace = true, default-features = true }
pezsc-authority-discovery = { workspace = true, default-features = true }
pezsc-basic-authorship = { workspace = true, default-features = true }
pezsc-chain-spec = { workspace = true, default-features = true }
pezsc-client-api = { workspace = true, default-features = true }
pezsc-consensus = { workspace = true, default-features = true }
pezsc-consensus-babe = { workspace = true, default-features = true }
pezsc-consensus-beefy = { workspace = true, default-features = true }
pezsc-consensus-grandpa = { workspace = true, default-features = true }
pezsc-consensus-slots = { workspace = true, default-features = true }
pezsc-executor = { workspace = true, default-features = true }
pezsc-keystore = { workspace = true, default-features = true }
pezsc-network = { workspace = true, default-features = true }
pezsc-network-sync = { workspace = true, default-features = true }
pezsc-offchain = { workspace = true, default-features = true }
pezsc-service = { workspace = true }
pezsc-sync-state-rpc = { workspace = true, default-features = true }
pezsc-sysinfo = { workspace = true, default-features = true }
pezsc-telemetry = { workspace = true, default-features = true }
pezsc-transaction-pool = { workspace = true, default-features = true }
pezsc-transaction-pool-api = { workspace = true, default-features = true }
pezsp-genesis-builder = { workspace = true, default-features = true }
pezsp-mmr-primitives = { workspace = true, default-features = true }

# Bizinikiwi Primitives
pezpallet-transaction-payment = { workspace = true, default-features = true }
pezsp-api = { workspace = true, default-features = true }
pezsp-authority-discovery = { workspace = true, default-features = true }
pezsp-block-builder = { workspace = true, default-features = true }
pezsp-blockchain = { workspace = true, default-features = true }
pezsp-consensus = { workspace = true, default-features = true }
pezsp-consensus-babe = { workspace = true, default-features = true }
pezsp-consensus-beefy = { workspace = true, default-features = true }
pezsp-consensus-grandpa = { workspace = true, default-features = true }
pezsp-core = { workspace = true, default-features = true }
pezsp-inherents = { workspace = true, default-features = true }
pezsp-io = { workspace = true, default-features = true }
pezsp-keyring = { workspace = true, default-features = true }
pezsp-offchain = { workspace = true, default-features = true }
pezsp-runtime = { workspace = true, default-features = true }
pezsp-session = { workspace = true, default-features = true }
pezsp-timestamp = { workspace = true, default-features = true }
pezsp-transaction-pool = { workspace = true, default-features = true }
pezsp-version = { workspace = true, default-features = true }
pezsp-weights = { workspace = true, default-features = true }

# Bizinikiwi Pallets
pezframe-metadata-hash-extension = { optional = true, workspace = true, default-features = true }
pezframe-system = { workspace = true, default-features = true }
pezpallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = true }

# Bizinikiwi Other
pezframe-benchmarking = { workspace = true, default-features = true }
pezframe-benchmarking-cli = { workspace = true, default-features = true }
pezframe-system-rpc-runtime-api = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }

# External Crates
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
gum = { workspace = true, default-features = true }
is_executable = { workspace = true }
kvdb = { workspace = true }
kvdb-rocksdb = { optional = true, workspace = true }
log = { workspace = true, default-features = true }
parity-db = { optional = true, workspace = true }
parking_lot = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }

# Pezkuwi
pezkuwi-core-primitives = { workspace = true, default-features = true }
pezkuwi-node-core-teyrchains-inherent = { workspace = true, default-features = true }
pezkuwi-node-network-protocol = { workspace = true, default-features = true }
pezkuwi-node-primitives = { workspace = true, default-features = true }
pezkuwi-node-subsystem = { workspace = true, default-features = true }
pezkuwi-node-subsystem-types = { workspace = true, default-features = true }
pezkuwi-node-subsystem-util = { workspace = true, default-features = true }
pezkuwi-overseer = { workspace = true, default-features = true }
pezkuwi-primitives = { workspace = true, default-features = true }
pezkuwi-rpc = { workspace = true, default-features = true }
pezkuwi-runtime-teyrchains = { workspace = true, default-features = true }

# Pezkuwi Runtime Constants
pezkuwichain-runtime-constants = { optional = true, workspace = true, default-features = true }
zagros-runtime-constants = { optional = true, workspace = true, default-features = true }

# Pezkuwi Runtimes
pezkuwichain-runtime = { optional = true, workspace = true }
zagros-runtime = { optional = true, workspace = true, default-features = true }

# Pezkuwi Subsystems
pezkuwi-approval-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-bitfield-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-availability-recovery = { optional = true, workspace = true, default-features = true }
pezkuwi-collator-protocol = { optional = true, workspace = true, default-features = true }
pezkuwi-dispute-distribution = { optional = true, workspace = true, default-features = true }
pezkuwi-gossip-support = { optional = true, workspace = true, default-features = true }
pezkuwi-network-bridge = { optional = true, workspace = true, default-features = true }
pezkuwi-node-collation-generation = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-approval-voting = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-approval-voting-parallel = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-av-store = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-backing = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-bitfield-signing = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-candidate-validation = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-chain-api = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-chain-selection = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-dispute-coordinator = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-prospective-teyrchains = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-provisioner = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-pvf = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-pvf-checker = { optional = true, workspace = true, default-features = true }
pezkuwi-node-core-runtime-api = { optional = true, workspace = true, default-features = true }
pezkuwi-statement-distribution = { optional = true, workspace = true, default-features = true }

xcm = { workspace = true, default-features = true }
xcm-runtime-apis = { workspace = true, default-features = true }

[dev-dependencies]
assert_matches = { workspace = true }
pezkuwi-node-subsystem-test-helpers = { workspace = true }
pezkuwi-primitives-test-helpers = { workspace = true }
pezkuwi-test-client = { workspace = true }
pezsp-tracing = { workspace = true }
tempfile = { workspace = true }

[features]
default = ["db", "full-node"]
db = ["pezsc-service/rocksdb"]
full-node = [
	"kvdb-rocksdb",
	"parity-db",
	"pezkuwi-approval-distribution",
	"pezkuwi-availability-bitfield-distribution",
	"pezkuwi-availability-distribution",
	"pezkuwi-availability-recovery",
	"pezkuwi-collator-protocol",
	"pezkuwi-dispute-distribution",
	"pezkuwi-gossip-support",
	"pezkuwi-network-bridge",
	"pezkuwi-node-collation-generation",
	"pezkuwi-node-core-approval-voting",
	"pezkuwi-node-core-approval-voting-parallel",
	"pezkuwi-node-core-av-store",
	"pezkuwi-node-core-backing",
	"pezkuwi-node-core-bitfield-signing",
	"pezkuwi-node-core-candidate-validation",
	"pezkuwi-node-core-chain-api",
	"pezkuwi-node-core-chain-selection",
	"pezkuwi-node-core-dispute-coordinator",
	"pezkuwi-node-core-prospective-teyrchains",
	"pezkuwi-node-core-provisioner",
	"pezkuwi-node-core-pvf",
	"pezkuwi-node-core-pvf-checker",
	"pezkuwi-node-core-runtime-api",
	"pezkuwi-statement-distribution",
]

# Configure the native runtimes to use.
zagros-native = [
	"pezframe-metadata-hash-extension",
	"zagros-runtime",
	"zagros-runtime-constants",
]
pezkuwichain-native = [
	"pezframe-metadata-hash-extension",
	"pezkuwichain-runtime",
	"pezkuwichain-runtime-constants",
]

# Generate the metadata hash needed for CheckMetadataHash
# in the test runtimes.
metadata-hash = [
	"pezkuwichain-runtime?/metadata-hash",
	"zagros-runtime?/metadata-hash",
]

runtime-benchmarks = [
	"pezframe-benchmarking-cli/runtime-benchmarks",
	"pezframe-benchmarking/runtime-benchmarks",
	"pezframe-metadata-hash-extension?/runtime-benchmarks",
	"pezframe-system-rpc-runtime-api/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"gum/runtime-benchmarks",
	"mmr-gadget/runtime-benchmarks",
	"pezpallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"pezpallet-transaction-payment/runtime-benchmarks",
	"pezkuwi-approval-distribution?/runtime-benchmarks",
	"pezkuwi-availability-bitfield-distribution?/runtime-benchmarks",
	"pezkuwi-availability-distribution?/runtime-benchmarks",
	"pezkuwi-availability-recovery?/runtime-benchmarks",
	"pezkuwi-collator-protocol?/runtime-benchmarks",
	"pezkuwi-core-primitives/runtime-benchmarks",
	"pezkuwi-dispute-distribution?/runtime-benchmarks",
	"pezkuwi-gossip-support?/runtime-benchmarks",
	"pezkuwi-network-bridge?/runtime-benchmarks",
	"pezkuwi-node-collation-generation?/runtime-benchmarks",
	"pezkuwi-node-core-approval-voting-parallel?/runtime-benchmarks",
	"pezkuwi-node-core-approval-voting?/runtime-benchmarks",
	"pezkuwi-node-core-av-store?/runtime-benchmarks",
	"pezkuwi-node-core-backing?/runtime-benchmarks",
	"pezkuwi-node-core-bitfield-signing?/runtime-benchmarks",
	"pezkuwi-node-core-candidate-validation?/runtime-benchmarks",
	"pezkuwi-node-core-chain-api?/runtime-benchmarks",
	"pezkuwi-node-core-chain-selection?/runtime-benchmarks",
	"pezkuwi-node-core-dispute-coordinator?/runtime-benchmarks",
	"pezkuwi-node-core-prospective-teyrchains?/runtime-benchmarks",
	"pezkuwi-node-core-provisioner?/runtime-benchmarks",
	"pezkuwi-node-core-pvf-checker?/runtime-benchmarks",
	"pezkuwi-node-core-pvf?/runtime-benchmarks",
	"pezkuwi-node-core-runtime-api?/runtime-benchmarks",
	"pezkuwi-node-core-teyrchains-inherent/runtime-benchmarks",
	"pezkuwi-node-network-protocol/runtime-benchmarks",
	"pezkuwi-node-primitives/runtime-benchmarks",
	"pezkuwi-node-subsystem-test-helpers/runtime-benchmarks",
	"pezkuwi-node-subsystem-types/runtime-benchmarks",
	"pezkuwi-node-subsystem-util/runtime-benchmarks",
	"pezkuwi-node-subsystem/runtime-benchmarks",
	"pezkuwi-overseer/runtime-benchmarks",
	"pezkuwi-primitives-test-helpers/runtime-benchmarks",
	"pezkuwi-primitives/runtime-benchmarks",
	"pezkuwi-rpc/runtime-benchmarks",
	"pezkuwi-runtime-teyrchains/runtime-benchmarks",
	"pezkuwi-statement-distribution?/runtime-benchmarks",
	"pezkuwi-test-client/runtime-benchmarks",
	"pezkuwichain-runtime-constants?/runtime-benchmarks",
	"pezkuwichain-runtime?/runtime-benchmarks",
	"pezsc-authority-discovery/runtime-benchmarks",
	"pezsc-basic-authorship/runtime-benchmarks",
	"pezsc-chain-spec/runtime-benchmarks",
	"pezsc-client-api/runtime-benchmarks",
	"pezsc-consensus-babe/runtime-benchmarks",
	"pezsc-consensus-beefy/runtime-benchmarks",
	"pezsc-consensus-grandpa/runtime-benchmarks",
	"pezsc-consensus-slots/runtime-benchmarks",
	"pezsc-consensus/runtime-benchmarks",
	"pezsc-executor/runtime-benchmarks",
	"pezsc-network-sync/runtime-benchmarks",
	"pezsc-network/runtime-benchmarks",
	"pezsc-offchain/runtime-benchmarks",
	"pezsc-service/runtime-benchmarks",
	"pezsc-sync-state-rpc/runtime-benchmarks",
	"pezsc-sysinfo/runtime-benchmarks",
	"pezsc-transaction-pool-api/runtime-benchmarks",
	"pezsc-transaction-pool/runtime-benchmarks",
	"pezsp-api/runtime-benchmarks",
	"pezsp-authority-discovery/runtime-benchmarks",
	"pezsp-block-builder/runtime-benchmarks",
	"pezsp-blockchain/runtime-benchmarks",
	"pezsp-consensus-babe/runtime-benchmarks",
	"pezsp-consensus-beefy/runtime-benchmarks",
	"pezsp-consensus-grandpa/runtime-benchmarks",
	"pezsp-consensus/runtime-benchmarks",
	"pezsp-genesis-builder/runtime-benchmarks",
	"pezsp-inherents/runtime-benchmarks",
	"pezsp-io/runtime-benchmarks",
	"pezsp-keyring/runtime-benchmarks",
	"pezsp-mmr-primitives/runtime-benchmarks",
	"pezsp-offchain/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"pezsp-session/runtime-benchmarks",
	"pezsp-timestamp/runtime-benchmarks",
	"pezsp-transaction-pool/runtime-benchmarks",
	"pezsp-version/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
	"xcm/runtime-benchmarks",
	"zagros-runtime-constants?/runtime-benchmarks",
	"zagros-runtime?/runtime-benchmarks",
]
try-runtime = [
	"pezframe-system/try-runtime",
	"pezpallet-transaction-payment/try-runtime",
	"pezkuwi-runtime-teyrchains/try-runtime",
	"pezkuwichain-runtime?/try-runtime",
	"pezsp-runtime/try-runtime",
	"zagros-runtime?/try-runtime",
]
fast-runtime = [
	"pezkuwichain-runtime?/fast-runtime",
	"zagros-runtime?/fast-runtime",
]

malus = ["full-node"]
runtime-metrics = [
	"pezkuwi-runtime-teyrchains/runtime-metrics",
	"pezkuwichain-runtime?/runtime-metrics",
	"zagros-runtime?/runtime-metrics",
]
