
//! Autogenerated weights for `pallet_presale`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-11-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// /home/mamostehp/Pezkuwi-SDK/target/release/pezkuwi
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_presale
// --extrinsic=create_presale,contribute,finalize_presale,cancel_presale,add_to_whitelist
// --steps=50
// --repeat=20
// --output=./pezkuwi/pallets/presale/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for pallet_presale.
pub trait WeightInfo {
	fn create_presale() -> Weight;
	fn contribute() -> Weight;
	fn finalize_presale(n: u32) -> Weight;
	fn refund() -> Weight;
	fn cancel_presale() -> Weight;
	fn add_to_whitelist() -> Weight;
	fn start_presale() -> Weight;
	fn emergency_pause() -> Weight;
}

/// Weight functions for `pallet_presale`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Presale::NextPresaleId` (r:1 w:1)
	/// Proof: `Presale::NextPresaleId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Presales` (r:0 w:1)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	fn create_presale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1489`
		// Minimum execution time: 12_038_000 picoseconds.
		Weight::from_parts(12_601_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributions` (r:1 w:1)
	/// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalRaised` (r:1 w:1)
	/// Proof: `Presale::TotalRaised` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributors` (r:1 w:1)
	/// Proof: `Presale::Contributors` (`max_values`: None, `max_size`: Some(320022), added: 322497, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalPlatformVolume` (r:1 w:1)
	/// Proof: `Presale::TotalPlatformVolume` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalPlatformFees` (r:1 w:1)
	/// Proof: `Presale::TotalPlatformFees` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn contribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1160`
		//  Estimated: `323487`
		// Minimum execution time: 157_602_000 picoseconds.
		Weight::from_parts(172_129_000, 0)
			.saturating_add(Weight::from_parts(0, 323487))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `Presale::TotalRaised` (r:1 w:0)
	/// Proof: `Presale::TotalRaised` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributors` (r:1 w:0)
	/// Proof: `Presale::Contributors` (`max_values`: None, `max_size`: Some(320022), added: 322497, mode: `MaxEncodedLen`)
	/// Storage: `Presale::Contributions` (r:100 w:0)
	/// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(110), added: 2585, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:101 w:101)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Presale::SuccessfulPresales` (r:1 w:1)
	/// Proof: `Presale::SuccessfulPresales` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn finalize_presale(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1061 + n * (258 ±0)`
		//  Estimated: `323487 + n * (2609 ±0)`
		// Minimum execution time: 76_082_000 picoseconds.
		Weight::from_parts(48_514_380, 0)
			.saturating_add(Weight::from_parts(0, 323487))
			// Standard Error: 87_179
			.saturating_add(Weight::from_parts(38_227_551, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2609).saturating_mul(n.into()))
	}
	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	fn cancel_presale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `3701`
		// Minimum execution time: 13_460_000 picoseconds.
		Weight::from_parts(14_058_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Proof: `Presale::Presales` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `Presale::WhitelistedAccounts` (r:0 w:1)
	/// Proof: `Presale::WhitelistedAccounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn add_to_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `235`
		//  Estimated: `3701`
		// Minimum execution time: 13_530_000 picoseconds.
		Weight::from_parts(14_289_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `Presale::Presales` (r:1 w:0)
	/// Storage: `Presale::Contributions` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Storage: `System::Account` (r:1 w:1)
	/// Storage: `Presale::TotalRaised` (r:1 w:1)
	/// Storage: `Presale::TotalPlatformFees` (r:1 w:1)
	/// Estimated based on contribute complexity
	fn refund() -> Weight {
		Weight::from_parts(150_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}

	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Estimated weight based on create_presale complexity
	fn start_presale() -> Weight {
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `Presale::Presales` (r:1 w:1)
	/// Estimated weight based on cancel_presale complexity
	fn emergency_pause() -> Weight {
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3701))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
