//! Autogenerated weights for `pallet_presale`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-11-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pezkuwichain`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/pezkuwi-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_presale
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/presale/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_presale`.
pub trait WeightInfo {
    fn start_presale() -> Weight;
    fn contribute() -> Weight;
    fn finalize_presale(n: u32) -> Weight;
    fn emergency_pause() -> Weight;
    fn emergency_unpause() -> Weight;
}

/// Weights for `pallet_presale` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Presale::PresaleActive` (r:1 w:1)
    /// Proof: `Presale::PresaleActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Presale::PresaleStartBlock` (r:0 w:1)
    /// Proof: `Presale::PresaleStartBlock` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Paused` (r:0 w:1)
    /// Proof: `Presale::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn start_presale() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    /// Storage: `Presale::PresaleActive` (r:1 w:0)
    /// Proof: `Presale::PresaleActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Paused` (r:1 w:0)
    /// Proof: `Presale::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Presale::PresaleStartBlock` (r:1 w:0)
    /// Proof: `Presale::PresaleStartBlock` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:2 w:2)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Contributions` (r:1 w:1)
    /// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Contributors` (r:1 w:1)
    /// Proof: `Presale::Contributors` (`max_values`: Some(1), `max_size`: Some(100002), added: 100497, mode: `MaxEncodedLen`)
    /// Storage: `Presale::TotalRaised` (r:1 w:1)
    /// Proof: `Presale::TotalRaised` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn contribute() -> Weight {
        Weight::from_parts(55_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(9))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    /// Storage: `Presale::PresaleActive` (r:1 w:1)
    /// Proof: `Presale::PresaleActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Presale::PresaleStartBlock` (r:1 w:0)
    /// Proof: `Presale::PresaleStartBlock` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Presale::TotalRaised` (r:1 w:0)
    /// Proof: `Presale::TotalRaised` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Contributors` (r:1 w:0)
    /// Proof: `Presale::Contributors` (`max_values`: Some(1), `max_size`: Some(100002), added: 100497, mode: `MaxEncodedLen`)
    /// Storage: `Presale::Contributions` (r:100 w:0)
    /// Proof: `Presale::Contributions` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:200 w:200)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 100]`.
    fn finalize_presale(n: u32, ) -> Weight {
        Weight::from_parts(25_000_000, 0)
            // Standard Error: 50_000
            .saturating_add(Weight::from_parts(15_000_000, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
    }

    /// Storage: `Presale::Paused` (r:0 w:1)
    /// Proof: `Presale::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn emergency_pause() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: `Presale::Paused` (r:0 w:1)
    /// Proof: `Presale::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn emergency_unpause() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn start_presale() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(3))
    }

    fn contribute() -> Weight {
        Weight::from_parts(55_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(9))
            .saturating_add(RocksDbWeight::get().writes(5))
    }

    fn finalize_presale(n: u32, ) -> Weight {
        Weight::from_parts(25_000_000, 0)
            .saturating_add(Weight::from_parts(15_000_000, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().reads((3_u64).saturating_mul(n.into())))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
    }

    fn emergency_pause() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1))
    }

    fn emergency_unpause() -> Weight {
        Weight::from_parts(12_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
