[package]
name = "snowbridge-runtime-test-common"
description = "Snowbridge Runtime Tests"
version = "0.2.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition.workspace = true
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/snowbridge-runtime-test-common"

[lints]
workspace = true

[package.metadata.pezkuwi-sdk]
exclude-from-umbrella = true

[dependencies]
codec = { features = ["derive"], workspace = true }

# Bizinikiwi
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
pezpallet-balances = { workspace = true }
pezpallet-message-queue = { workspace = true }
pezpallet-session = { workspace = true }
pezpallet-timestamp = { workspace = true }
pezpallet-utility = { workspace = true }
pezsp-core = { workspace = true }
pezsp-io = { workspace = true }
pezsp-keyring = { workspace = true, default-features = true }
pezsp-runtime = { workspace = true }

# Pezkuwi
pezpallet-xcm = { workspace = true }
xcm = { workspace = true }
xcm-executor = { workspace = true }

# Pezcumulus
pezcumulus-pezpallet-teyrchain-system = { workspace = true }
pezpallet-collator-selection = { workspace = true }
teyrchain-info = { workspace = true }
teyrchains-runtimes-test-utils = { workspace = true }

# Ethereum Bridge (Snowbridge)
snowbridge-core = { workspace = true }
snowbridge-pezpallet-ethereum-client = { workspace = true }
snowbridge-pezpallet-ethereum-client-fixtures = { workspace = true }
snowbridge-pezpallet-outbound-queue = { workspace = true }
snowbridge-pezpallet-system = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "pezcumulus-pezpallet-teyrchain-system/std",
  "pezframe-support/std",
  "pezframe-system/std",
  "pezpallet-balances/std",
  "pezpallet-collator-selection/std",
  "pezpallet-message-queue/std",
  "pezpallet-session/std",
  "pezpallet-timestamp/std",
  "pezpallet-utility/std",
  "pezpallet-xcm/std",
  "snowbridge-core/std",
  "snowbridge-pezpallet-ethereum-client-fixtures/std",
  "snowbridge-pezpallet-ethereum-client/std",
  "snowbridge-pezpallet-outbound-queue/std",
  "snowbridge-pezpallet-system/std",
  "pezsp-core/std",
  "pezsp-io/std",
  "pezsp-keyring/std",
  "pezsp-runtime/std",
  "teyrchain-info/std",
  "teyrchains-runtimes-test-utils/std",
  "xcm-executor/std",
  "xcm/std",
]

runtime-benchmarks = [
  "pezcumulus-pezpallet-teyrchain-system/runtime-benchmarks",
  "pezframe-support/runtime-benchmarks",
  "pezframe-system/runtime-benchmarks",
  "pezpallet-balances/runtime-benchmarks",
  "pezpallet-collator-selection/runtime-benchmarks",
  "pezpallet-message-queue/runtime-benchmarks",
  "pezpallet-session/runtime-benchmarks",
  "pezpallet-timestamp/runtime-benchmarks",
  "pezpallet-utility/runtime-benchmarks",
  "pezpallet-xcm/runtime-benchmarks",
  "snowbridge-core/runtime-benchmarks",
  "snowbridge-pezpallet-ethereum-client-fixtures/runtime-benchmarks",
  "snowbridge-pezpallet-ethereum-client/runtime-benchmarks",
  "snowbridge-pezpallet-outbound-queue/runtime-benchmarks",
  "snowbridge-pezpallet-system/runtime-benchmarks",
  "pezsp-io/runtime-benchmarks",
  "pezsp-keyring/runtime-benchmarks",
  "pezsp-runtime/runtime-benchmarks",
  "teyrchain-info/runtime-benchmarks",
  "teyrchains-runtimes-test-utils/runtime-benchmarks",
  "xcm-executor/runtime-benchmarks",
  "xcm/runtime-benchmarks",
]
fast-runtime = []
