[relaychain]
default_command = "pezkuwi"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000
chain_spec_path = "./dev_chain_spec.json"

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "pezkuwi-omni-node"
