[package]
name = "pezcumulus-zombienet-sdk-helpers"
version = "0.1.0"
description = "Zomebienet-sdk helpers for teyrchain related tests."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true, default-features = true }
codec = { workspace = true, features = ["derive"] }
log = { workspace = true }
pezkuwi-primitives = { workspace = true, default-features = true }
pezcumulus-primitives-core = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
zombienet-sdk = { workspace = true }
futures = { workspace = true }
zombienet-configuration = { workspace = true }

[features]
runtime-benchmarks = [
  "pezcumulus-primitives-core/runtime-benchmarks",
  "pezkuwi-primitives/runtime-benchmarks",
]
