[package]
name = "pezpallet-staking-async-preset-store"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
description = "Simple pezpallet to store the preset used to generate a runtime's genesis in state"
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true


[dependencies]
codec = { workspace = true }
frame = { workspace = true, features = ["runtime"] }
pezpallet-staking-async-ah-client = { workspace = true }
scale-info = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"pezpallet-staking-async-ah-client/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pezpallet-staking-async-ah-client/runtime-benchmarks",
]
