[package]
name = "bp-pezkuwi-bulletin"
description = "Primitives of Pezkuwi Bulletin chain runtime."
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
documentation.workspace = true
homepage = { workspace = true }

[package.metadata.pezkuwi-sdk]
exclude-from-umbrella = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }

# Bridge Dependencies
bp-header-pez-chain = { workspace = true }
bp-messages = { workspace = true }
bp-pezkuwi-core = { workspace = true }
pezbp-runtime = { workspace = true }

# Bizinikiwi Based Dependencies
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
pezsp-api = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"bp-header-pez-chain/std",
	"bp-messages/std",
	"bp-pezkuwi-core/std",
	"codec/std",
	"pezbp-runtime/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezsp-api/std",
	"pezsp-runtime/std",
	"pezsp-std/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"bp-header-pez-chain/runtime-benchmarks",
	"bp-messages/runtime-benchmarks",
	"bp-pezkuwi-core/runtime-benchmarks",
	"pezbp-runtime/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezsp-api/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
]
