// This file is part of Bizinikiwi.

// Copyright (C) Parity Technologies (UK) Ltd. and Dijital Kurdistan Tech Institute
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pezpallet_perwerde`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE BIZINIKIWI BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-12-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MamostePC`, CPU: `11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/frame-omni-bencher
// v1
// benchmark
// pezpallet
// --runtime
// target/release/wbuild/people-pezkuwichain-runtime/people_pezkuwichain_runtime.compact.compressed.wasm
// --pallets
// pezpallet_perwerde
// -e
// all
// --steps
// 50
// --repeat
// 20
// --output
// pezcumulus/teyrchains/pezpallets/perwerde/src/weights.rs
// --template
// bizinikiwi/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use pezframe_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pezpallet_perwerde`.
pub trait WeightInfo {
	fn create_course() -> Weight;
	fn enroll() -> Weight;
	fn complete_course() -> Weight;
	fn archive_course() -> Weight;
}

/// Weights for `pezpallet_perwerde` using the Bizinikiwi node and recommended hardware.
pub struct BizinikiwiWeight<T>(PhantomData<T>);
impl<T: pezframe_system::Config> WeightInfo for BizinikiwiWeight<T> {
	/// Storage: `Perwerde::NextCourseId` (r:1 w:1)
	/// Proof: `Perwerde::NextCourseId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Courses` (r:0 w:1)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	fn create_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1489`
		// Minimum execution time: 21_032_000 picoseconds.
		Weight::from_parts(22_777_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:0)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Enrollments` (r:1 w:1)
	/// Proof: `Perwerde::Enrollments` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::StudentCourses` (r:1 w:1)
	/// Proof: `Perwerde::StudentCourses` (`max_values`: None, `max_size`: Some(249), added: 2724, mode: `MaxEncodedLen`)
	fn enroll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `4428`
		// Minimum execution time: 33_652_000 picoseconds.
		Weight::from_parts(37_083_000, 4428)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:0)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Enrollments` (r:1 w:1)
	/// Proof: `Perwerde::Enrollments` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	fn complete_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `4428`
		// Minimum execution time: 33_123_000 picoseconds.
		Weight::from_parts(37_458_000, 4428)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:1)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	fn archive_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `4428`
		// Minimum execution time: 24_529_000 picoseconds.
		Weight::from_parts(27_529_000, 4428)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Perwerde::NextCourseId` (r:1 w:1)
	/// Proof: `Perwerde::NextCourseId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Courses` (r:0 w:1)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	fn create_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3`
		//  Estimated: `1489`
		// Minimum execution time: 21_032_000 picoseconds.
		Weight::from_parts(22_777_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:0)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Enrollments` (r:1 w:1)
	/// Proof: `Perwerde::Enrollments` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::StudentCourses` (r:1 w:1)
	/// Proof: `Perwerde::StudentCourses` (`max_values`: None, `max_size`: Some(249), added: 2724, mode: `MaxEncodedLen`)
	fn enroll() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `4428`
		// Minimum execution time: 33_652_000 picoseconds.
		Weight::from_parts(37_083_000, 4428)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:0)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::Enrollments` (r:1 w:1)
	/// Proof: `Perwerde::Enrollments` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
	fn complete_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `4428`
		// Minimum execution time: 33_123_000 picoseconds.
		Weight::from_parts(37_458_000, 4428)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Perwerde::Courses` (r:1 w:1)
	/// Proof: `Perwerde::Courses` (`max_values`: None, `max_size`: Some(963), added: 3438, mode: `MaxEncodedLen`)
	fn archive_course() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `149`
		//  Estimated: `4428`
		// Minimum execution time: 24_529_000 picoseconds.
		Weight::from_parts(27_529_000, 4428)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
