name: RC Build

on:
  workflow_call:
    inputs:
      binary:
        description: Binary to be build for the release
        required: true
        default: pezkuwi
        type: string

      package:
        description: Package to be built, for now can be pezkuwi, pezkuwi-parachain-bin, or pezkuwi-omni-node
        required: true
        type: string

      release_tag:
        description: Tag matching the actual release candidate with the format pezkuwi-stableYYMM(-rcX) or pezkuwi-stableYYMM-X(-rcX)
        required: true
        type: string

      target:
        description: Target triple for which the artifacts are being built (e.g. x86_64-unknown-linux-gnu)
        required: true
        type: string

    secrets:
      PGP_KMS_KEY:
        required: true
      PGP_KMS_HASH:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_RELEASE_ACCESS_KEY_ID:
        required: true
      AWS_RELEASE_SECRET_ACCESS_KEY:
        required: true

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:

  set-image:
    # GitHub Actions allows using 'env' in a container context.
    # However, env variables don't work for forks: https://github.com/orgs/community/discussions/44322
    # This workaround sets the container image for each job using 'set-image' job output.
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.set_image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.0

      - id: set_image
        run: cat .github/env >> $GITHUB_OUTPUT

  build-rc:
    if: ${{ inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [set-image]
    runs-on: ubuntu-latest-m
    environment: release
    container:
      image: ${{ needs.set-image.outputs.IMAGE }}
    strategy:
      matrix:
        binaries: ${{ fromJSON(inputs.binary) }}
    env:
      PGP_KMS_KEY: ${{ secrets.PGP_KMS_KEY }}
      PGP_KMS_HASH: ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Install pgpkkms
        run: |
          # Install pgpkms that is used to sign built artifacts
          python3 -m pip install "pgpkms @ git+https://github.com/paritytech-release/pgpkms.git@e7f806f99e9be5c52f0b4a536b7d4ef9c3e695ed"
          which pgpkms

      - name: Checkout sources
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.0
        with:
          ref: ${{ inputs.release_tag }}
          fetch-depth: 0

      - name: Import gpg keys
        shell: bash
        run: |
          . ./.github/scripts/common/lib.sh

          import_gpg_keys

      - name: Build binary
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}" #avoid "detected dubious ownership" error
          ./.github/scripts/release/build-linux-release.sh ${{ matrix.binaries }} ${{ inputs.package }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: /artifacts/${{ matrix.binaries }}/${{ matrix.binaries }}

      - name: Sign artifacts
        working-directory: /artifacts/${{ matrix.binaries }}
        run: |
          python3 -m pgpkms sign --input ${{matrix.binaries }} -o ${{ matrix.binaries }}.asc

      - name: Check sha256 ${{ matrix.binaries }}
        working-directory: /artifacts/${{ matrix.binaries }}
        shell: bash
        run: |
          .  "${GITHUB_WORKSPACE}"/.github/scripts/common/lib.sh

          echo "Checking binary  ${{ matrix.binaries }}"
          check_sha256  ${{ matrix.binaries }}

      - name: Check GPG ${{ matrix.binaries }}
        working-directory: /artifacts/${{ matrix.binaries }}
        shell: bash
        run: |
          . "${GITHUB_WORKSPACE}"/.github/scripts/common/lib.sh

          check_gpg  ${{ matrix.binaries }}

      - name: Upload ${{ matrix.binaries }} artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.binaries }}_${{ inputs.target }}
          path: /artifacts/${{ matrix.binaries }}

  build-macos-rc:
    if: ${{ inputs.target == 'aarch64-apple-darwin' }}
    runs-on: parity-macos
    environment: release
    strategy:
      matrix:
        binaries: ${{ fromJSON(inputs.binary) }}
    env:
      PGP_KMS_KEY: ${{ secrets.PGP_KMS_KEY }}
      PGP_KMS_HASH: ${{ secrets.PGP_KMS_HASH }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.0
        with:
          ref: ${{ inputs.release_tag }}
          fetch-depth: 0

      - name: Set rust version from env file
        run: |
          RUST_VERSION=$(cat .github/env | sed -E 's/.*ci-unified:([^-]+)-([^-]+).*/\2/')
          echo $RUST_VERSION
          echo "RUST_VERSION=${RUST_VERSION}" >> $GITHUB_ENV
      - name: Set workspace environment variable
        # relevant for artifacts upload, which can not interpolate Github Action variable syntax when
        # used within valid paths. We can not use root-based paths either, since it is set as read-only
        # on the `parity-macos` runner.
        run: echo "ARTIFACTS_PATH=${GITHUB_WORKSPACE}/artifacts/${{ matrix.binaries }}" >> $GITHUB_ENV

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1ccc07ccd54b6048295516a3eb89b192c35057dc # master from 12.09.2024
      - name: Set homebrew binaries location on path
        run: echo "/opt/homebrew/bin" >>  $GITHUB_PATH

      - name: Install rust ${{ env.RUST_VERSION }}
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          cache: false
          toolchain: ${{ env.RUST_VERSION }}
          target: wasm32-unknown-unknown
          components: cargo, clippy, rust-docs, rust-src, rustfmt, rustc, rust-std

      - name: cargo info
        run: |
          echo "######## rustup show ########"
          rustup show
          echo "######## cargo --version ########"
          cargo --version

      - name: Install protobuf
        run: brew install protobuf
      - name: Install gpg
        run: |
          brew install gnupg
          # Setup for being able to resolve: keyserver.ubuntu.com.
          # See: https://github.com/actions/runner-images/issues/9777
          mkdir -p ~/.gnupg/
          touch ~/.gnupg/dirmngr.conf
          echo "standard-resolver" >  ~/.gnupg/dirmngr.conf
      - name: Install sha256sum
        run: |
          brew install coreutils

      - name: Install pgpkkms
        run: |
          # Install pgpkms that is used to sign built artifacts
          python3 -m pip  install "pgpkms @ git+https://github.com/paritytech-release/pgpkms.git@e7f806f99e9be5c52f0b4a536b7d4ef9c3e695ed" --break-system-packages

      - name: Import gpg keys
        shell: bash
        run: |
          . ./.github/scripts/common/lib.sh

          import_gpg_keys

      - name: Build binary
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}" #avoid "detected dubious ownership" error
          ./.github/scripts/release/build-macos-release.sh ${{ matrix.binaries }} ${{ inputs.package }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: ${{ env.ARTIFACTS_PATH }}/${{ matrix.binaries }}

      - name: Sign artifacts
        working-directory: ${{ env.ARTIFACTS_PATH }}
        run: |
          python3 -m pgpkms sign --input ${{matrix.binaries }} -o ${{ matrix.binaries }}.asc

      - name: Check sha256 ${{ matrix.binaries }}
        working-directory: ${{ env.ARTIFACTS_PATH }}
        shell: bash
        run: |
          .  "${GITHUB_WORKSPACE}"/.github/scripts/common/lib.sh

          echo "Checking binary  ${{ matrix.binaries }}"
          check_sha256  ${{ matrix.binaries }}

      - name: Check GPG ${{ matrix.binaries }}
        working-directory: ${{ env.ARTIFACTS_PATH }}
        shell: bash
        run: |
          . "${GITHUB_WORKSPACE}"/.github/scripts/common/lib.sh

          check_gpg  ${{ matrix.binaries }}

      - name: Upload ${{ matrix.binaries }} artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.binaries }}_${{ inputs.target }}
          path: ${{ env.ARTIFACTS_PATH }}

  build-pezkuwi-deb-package:
    if: ${{ inputs.package == 'pezkuwi' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-rc]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.0
      with:
        ref: ${{ inputs.release_tag }}
        fetch-depth: 0

    - name: Download pezkuwi_x86_64-unknown-linux-gnu artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: pezkuwi_x86_64-unknown-linux-gnu
        path: target/production
        merge-multiple: true

    - name: Download pezkuwi-execute-worker_x86_64-unknown-linux-gnu artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: pezkuwi-execute-worker_x86_64-unknown-linux-gnu
        path: target/production
        merge-multiple: true

    - name: Download pezkuwi-prepare-worker_x86_64-unknown-linux-gnu artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: pezkuwi-prepare-worker_x86_64-unknown-linux-gnu
        path: target/production
        merge-multiple: true

    - name: Build pezkuwi deb package
      shell: bash
      run: |
        . "${GITHUB_WORKSPACE}"/.github/scripts/common/lib.sh
        VERSION=$(get_pezkuwi_node_version_from_code)
        . "${GITHUB_WORKSPACE}"/.github/scripts/release/build-deb.sh ${{ inputs.package }} ${VERSION}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
      with:
        subject-path: target/production/*.deb

    - name: Upload ${{inputs.package }} artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ inputs.package }}_${{ inputs.target }}
        path: target/production
        overwrite: true

  upload-pezkuwi-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-pezkuwi-deb-package]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-parachain-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi-parachain-bin' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: pezkuwi-parachain
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-omni-node-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi-omni-node' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-frame-omni-bencher-artifacts-to-s3:
    if: ${{ inputs.package == 'frame-omni-bencher' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-chain-spec-builder-artifacts-to-s3:
    if: ${{ inputs.package == 'staging-chain-spec-builder' && inputs.target == 'x86_64-unknown-linux-gnu' }}
    needs: [build-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: chain-spec-builder
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi' && inputs.target == 'aarch64-apple-darwin' }}
    # TODO: add and use a `build-pezkuwi-homebrew-package` which packs all `pezkuwi` binaries:
    # `pezkuwi`, `pezkuwi-prepare-worker` and `pezkuwi-execute-worker`.
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-prepare-worker-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: pezkuwi-prepare-worker
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-execute-worker-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: pezkuwi-execute-worker
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-omni-node-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi-omni-node' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-pezkuwi-parachain-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'pezkuwi-parachain-bin' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: pezkuwi-parachain
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-frame-omni-bencher-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'frame-omni-bencher' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: ${{ inputs.package }}
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}

  upload-chain-spec-builder-macos-artifacts-to-s3:
    if: ${{ inputs.package == 'staging-chain-spec-builder' && inputs.target == 'aarch64-apple-darwin' }}
    needs: [build-macos-rc]
    uses: ./.github/workflows/release-reusable-s3-upload.yml
    with:
      package: chain-spec-builder
      release_tag: ${{ inputs.release_tag }}
      target: ${{ inputs.target }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_RELEASE_ACCESS_KEY_ID: ${{ secrets.AWS_RELEASE_ACCESS_KEY_ID }}
      AWS_RELEASE_SECRET_ACCESS_KEY: ${{ secrets.AWS_RELEASE_SECRET_ACCESS_KEY }}
